SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF SCHEMA_ID(N'core') IS NULL EXEC(N'CREATE SCHEMA [core] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'iam') IS NULL EXEC(N'CREATE SCHEMA [iam] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'consent') IS NULL EXEC(N'CREATE SCHEMA [consent] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'event') IS NULL EXEC(N'CREATE SCHEMA [event] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'social') IS NULL EXEC(N'CREATE SCHEMA [social] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'chat') IS NULL EXEC(N'CREATE SCHEMA [chat] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'storage') IS NULL EXEC(N'CREATE SCHEMA [storage] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'notification') IS NULL EXEC(N'CREATE SCHEMA [notification] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'nlp') IS NULL EXEC(N'CREATE SCHEMA [nlp] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'moderation') IS NULL EXEC(N'CREATE SCHEMA [moderation] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'ops') IS NULL EXEC(N'CREATE SCHEMA [ops] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'analytics') IS NULL EXEC(N'CREATE SCHEMA [analytics] AUTHORIZATION dbo');
GO
IF SCHEMA_ID(N'admin') IS NULL EXEC(N'CREATE SCHEMA [admin] AUTHORIZATION dbo');
GO

IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE name = N'MessageSequence' AND schema_id = SCHEMA_ID(N'chat'))
    EXEC(N'CREATE SEQUENCE chat.MessageSequence AS bigint START WITH 1 INCREMENT BY 1 CACHE 100');
GO

IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE name = N'SyncChangeSequence' AND schema_id = SCHEMA_ID(N'ops'))
    EXEC(N'CREATE SEQUENCE ops.SyncChangeSequence AS bigint START WITH 1 INCREMENT BY 1 CACHE 100');
GO
