-- core.community: Network/community boundary; one OLGA row in Release 1.
CREATE TABLE IF NOT EXISTS core.community (
        community_id varchar(64) NOT NULL, -- Stable API identifier.
        name varchar(200) NOT NULL, -- Display name.
        status varchar(24) NOT NULL CONSTRAINT df_community_status DEFAULT ('ACTIVE'), -- ACTIVE, SUSPENDED or CLOSED.
        default_locale varchar(16) NOT NULL CONSTRAINT df_community_default_locale DEFAULT ('en'), -- BCP-47 default locale.
        created_at timestamptz NOT NULL CONSTRAINT df_community_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_community_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_community_ PRIMARY KEY (community_id)
    );
-- iam.member: Authoritative member account and lifecycle state.
CREATE TABLE IF NOT EXISTS iam.member (
        member_id varchar(64) NOT NULL, -- Opaque identifier; use GUID/ULID string.
        community_id varchar(64) NOT NULL, -- FK core.community.
        status varchar(24) NOT NULL CONSTRAINT df_member_status DEFAULT ('PENDING'), -- PENDING, ACTIVE, SUSPENDED, ANONYMIZED, DELETED.
        locale varchar(16) NOT NULL CONSTRAINT df_member_locale DEFAULT ('en'), -- Preferred locale.
        verified_at timestamptz NULL, -- First completed account verification.
        suspended_at timestamptz NULL, -- Administrative suspension time.
        deleted_at timestamptz NULL, -- Deletion/anonymization workflow start.
        created_at timestamptz NOT NULL CONSTRAINT df_member_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_member_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_member_ PRIMARY KEY (member_id)
    );
-- iam.member_identity: Email/mobile/passwordless/Entra identity mapping.
CREATE TABLE IF NOT EXISTS iam.member_identity (
        member_identity_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Internal key.
        member_id varchar(64) NOT NULL, -- FK iam.member.
        provider varchar(32) NOT NULL, -- EMAIL, PHONE, ENTRA or approved provider.
        provider_subject_hash char(64) NOT NULL, -- Keyed deterministic hash used for equality lookup and uniqueness.
        provider_subject_ciphertext bytea NOT NULL, -- Encrypted normalized email/mobile or external subject.
        display_hint varchar(80) NULL, -- Masked support hint; never authoritative.
        is_primary boolean NOT NULL CONSTRAINT df_member_identity_is_primary DEFAULT (false), -- Primary sign-in identity flag.
        verified_at timestamptz NULL, -- Verification completion.
        last_login_at timestamptz NULL, -- Security/account support signal.
        created_at timestamptz NOT NULL CONSTRAINT df_member_identity_created_at DEFAULT (CURRENT_TIMESTAMP), -- Creation time.
        CONSTRAINT pk_member_identity_ PRIMARY KEY (member_identity_id)
    );
-- iam.permission: Controlled application permission catalog used by API authorization policies.
CREATE TABLE IF NOT EXISTS iam.permission (
        permission_code varchar(96) NOT NULL, -- Stable application permission code.
        resource_type varchar(64) NOT NULL, -- Protected application resource.
        action varchar(32) NOT NULL, -- READ, CREATE, UPDATE, DELETE, APPROVE, EXPORT or CONFIGURE.
        description varchar(500) NULL, -- Human-readable authorization intent.
        status varchar(16) NOT NULL CONSTRAINT df_permission_status DEFAULT ('ACTIVE'), -- ACTIVE or RETIRED.
        created_at timestamptz NOT NULL CONSTRAINT df_permission_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_permission_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_permission_ PRIMARY KEY (permission_code)
    );
-- iam.role_permission: Versioned mapping from application roles to permissions.
CREATE TABLE IF NOT EXISTS iam.role_permission (
        role_code varchar(64) NOT NULL, -- FK iam.role.
        permission_code varchar(96) NOT NULL, -- FK iam.permission.
        granted_at timestamptz NOT NULL CONSTRAINT df_role_permission_granted_at DEFAULT (CURRENT_TIMESTAMP), -- Grant time.
        granted_by varchar(64) NULL, -- Administrator approving the grant.
        revoked_at timestamptz NULL, -- Revocation time; null while active.
        CONSTRAINT pk_role_permission_ PRIMARY KEY (role_code, permission_code)
    );
-- iam.role: Controlled role catalog for member and administrator authorization.
CREATE TABLE IF NOT EXISTS iam.role (
        role_code varchar(64) NOT NULL, -- MEMBER, ADMIN, MODERATOR, NLP_EVALUATOR.
        name varchar(100) NOT NULL, -- Display name.
        description varchar(500) NULL, -- Scope and intended use.
        is_privileged boolean NOT NULL CONSTRAINT df_role_is_privileged DEFAULT (false), -- Requires elevated authentication and audit.
        created_at timestamptz NOT NULL CONSTRAINT df_role_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_role_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_role_ PRIMARY KEY (role_code)
    );
-- iam.auth_session: Application session binding and revocation state; no bearer or refresh tokens.
CREATE TABLE IF NOT EXISTS iam.auth_session (
        session_id varchar(64) NOT NULL, -- Opaque application session identifier.
        member_id varchar(64) NOT NULL, -- FK iam.member.
        device_id varchar(64) NULL, -- Optional FK iam.member_device.
        identity_provider varchar(32) NOT NULL, -- Approved CIAM provider.
        provider_session_hash char(64) NULL, -- Hash of provider session reference; never store tokens.
        auth_strength varchar(24) NOT NULL CONSTRAINT df_auth_session_auth_strength DEFAULT ('STANDARD'), -- STANDARD, MFA or STEP_UP.
        issued_at timestamptz NOT NULL CONSTRAINT df_auth_session_issued_at DEFAULT (CURRENT_TIMESTAMP), -- Session issue time.
        expires_at timestamptz NOT NULL, -- Hard application expiry.
        last_seen_at timestamptz NOT NULL CONSTRAINT df_auth_session_last_seen_at DEFAULT (CURRENT_TIMESTAMP), -- Last validated request.
        revoked_at timestamptz NULL, -- Immediate logout, deletion or compromise revocation.
        revocation_reason varchar(64) NULL, -- Controlled reason code.
        created_at timestamptz NOT NULL CONSTRAINT df_auth_session_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_auth_session_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_auth_session_ PRIMARY KEY (session_id)
    );
-- iam.member_role: role assignment with optional expiry.
CREATE TABLE IF NOT EXISTS iam.member_role (
        member_id varchar(64) NOT NULL, -- FK iam.member.
        role_code varchar(64) NOT NULL, -- FK iam.role.
        granted_by varchar(64) NULL, -- Administrator member ID.
        granted_at timestamptz NOT NULL CONSTRAINT df_member_role_granted_at DEFAULT (CURRENT_TIMESTAMP), -- Grant time.
        expires_at timestamptz NULL, -- Optional expiry.
        revoked_at timestamptz NULL, -- Revocation time.
        CONSTRAINT pk_member_role_ PRIMARY KEY (member_id, role_code)
    );
-- iam.member_device: Registered mobile installation and security state.
CREATE TABLE IF NOT EXISTS iam.member_device (
        device_id varchar(64) NOT NULL, -- Client installation identifier, rotated on reinstall.
        member_id varchar(64) NOT NULL, -- FK iam.member.
        platform varchar(16) NOT NULL, -- IOS or ANDROID.
        app_version varchar(32) NOT NULL, -- Last reported app version.
        status varchar(20) NOT NULL CONSTRAINT df_member_device_status DEFAULT ('ACTIVE'), -- ACTIVE or REVOKED.
        last_seen_at timestamptz NOT NULL CONSTRAINT df_member_device_last_seen_at DEFAULT (CURRENT_TIMESTAMP), -- Last authenticated request.
        revoked_at timestamptz NULL, -- Remote logout/device loss handling.
        created_at timestamptz NOT NULL CONSTRAINT df_member_device_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_member_device_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_member_device_ PRIMARY KEY (device_id)
    );
-- core.organization: Professional organization represented in profiles.
CREATE TABLE IF NOT EXISTS core.organization (
        organization_id varchar(64) NOT NULL, -- Stable identifier.
        community_id varchar(64) NOT NULL, -- FK core.community.
        name varchar(250) NOT NULL, -- Canonical organization name.
        normalized_name varchar(250) NOT NULL, -- Search/deduplication form.
        website_domain varchar(255) NULL, -- Verified domain when available.
        industry_code varchar(64) NULL, -- Reference taxonomy.
        verification_status varchar(24) NOT NULL CONSTRAINT df_organization_verification_status DEFAULT ('UNVERIFIED'), -- UNVERIFIED, PENDING, VERIFIED, REJECTED.
        status varchar(20) NOT NULL CONSTRAINT df_organization_status DEFAULT ('ACTIVE'), -- Lifecycle state.
        created_at timestamptz NOT NULL CONSTRAINT df_organization_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_organization_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_organization_ PRIMARY KEY (organization_id)
    );
-- core.organization_member: member affiliation, title and organization-level role.
CREATE TABLE IF NOT EXISTS core.organization_member (
        organization_member_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Internal key.
        organization_id varchar(64) NOT NULL, -- FK core.organization.
        member_id varchar(64) NOT NULL, -- FK iam.member.
        job_title varchar(200) NULL, -- Professional title.
        department varchar(150) NULL, -- Optional function/department.
        is_primary boolean NOT NULL CONSTRAINT df_organization_member_is_primary DEFAULT (false), -- Primary current affiliation.
        started_on date NULL, -- Optional month/day precision per product policy.
        ended_on date NULL, -- Null for current affiliation.
        created_at timestamptz NOT NULL CONSTRAINT df_organization_member_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_organization_member_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_organization_member_ PRIMARY KEY (organization_member_id)
    );
-- core.member_profile: Searchable professional profile and visibility state.
CREATE TABLE IF NOT EXISTS core.member_profile (
        member_id varchar(64) NOT NULL, -- One-to-one FK iam.member.
        display_name varchar(150) NOT NULL, -- member-facing name.
        headline varchar(240) NULL, -- Short professional headline.
        professional_summary varchar(2000) NULL, -- member-authored summary.
        role_category varchar(64) NULL, -- Controlled role/function code.
        profile_status varchar(24) NOT NULL CONSTRAINT df_member_profile_profile_status DEFAULT ('DRAFT'), -- DRAFT, PENDING_REVIEW, ACTIVE, HIDDEN.
        visibility varchar(20) NOT NULL CONSTRAINT df_member_profile_visibility DEFAULT ('MEMBERS'), -- PRIVATE, MEMBERS or CONTEXT_ONLY.
        completeness_score numeric(5,2) NOT NULL CONSTRAINT df_member_profile_completeness_score DEFAULT (0), -- Derived profile completeness percentage.
        published_at timestamptz NULL, -- First/current publication time.
        created_at timestamptz NOT NULL CONSTRAINT df_member_profile_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_member_profile_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_member_profile_ PRIMARY KEY (member_id)
    );
-- core.sector: Controlled sector/industry taxonomy.
CREATE TABLE IF NOT EXISTS core.sector (
        sector_code varchar(64) NOT NULL, -- Stable taxonomy code.
        parent_sector_code varchar(64) NULL, -- Self-referencing hierarchy.
        name varchar(150) NOT NULL, -- Display label.
        status varchar(16) NOT NULL CONSTRAINT df_sector_status DEFAULT ('ACTIVE'), -- ACTIVE or RETIRED.
        sort_order int NOT NULL CONSTRAINT df_sector_sort_order DEFAULT (0), -- Presentation order.
        created_at timestamptz NOT NULL CONSTRAINT df_sector_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_sector_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_sector_ PRIMARY KEY (sector_code)
    );
-- core.member_sector: Many-to-many profile sector selection.
CREATE TABLE IF NOT EXISTS core.member_sector (
        member_id varchar(64) NOT NULL, -- FK member_profile.
        sector_code varchar(64) NOT NULL, -- FK sector.
        is_primary boolean NOT NULL CONSTRAINT df_member_sector_is_primary DEFAULT (false), -- Primary sector flag.
        created_at timestamptz NOT NULL CONSTRAINT df_member_sector_created_at DEFAULT (CURRENT_TIMESTAMP), -- Assignment time.
        CONSTRAINT pk_member_sector_ PRIMARY KEY (member_id, sector_code)
    );
-- core.member_geography: member operating markets; not live location.
CREATE TABLE IF NOT EXISTS core.member_geography (
        member_geography_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Internal key.
        member_id varchar(64) NOT NULL, -- FK member_profile.
        country_code char(2) NOT NULL, -- ISO 3166-1 alpha-2.
        region varchar(120) NULL, -- State/region.
        city varchar(120) NULL, -- Operating city.
        is_primary boolean NOT NULL CONSTRAINT df_member_geography_is_primary DEFAULT (false), -- Primary market.
        created_at timestamptz NOT NULL CONSTRAINT df_member_geography_created_at DEFAULT (CURRENT_TIMESTAMP), -- Creation time.
        CONSTRAINT pk_member_geography_ PRIMARY KEY (member_geography_id)
    );
-- core.profile_field_visibility: Per-field exposure before/after connection.
CREATE TABLE IF NOT EXISTS core.profile_field_visibility (
        member_id varchar(64) NOT NULL, -- FK member_profile.
        field_code varchar(64) NOT NULL, -- PROFILE_SUMMARY, ORGANIZATION, GEOGRAPHY, etc.
        audience varchar(24) NOT NULL CONSTRAINT df_profile_field_visibility_audience DEFAULT ('CONNECTED'), -- PRIVATE, MATCHED, CONNECTED, MEMBERS.
        updated_at timestamptz NOT NULL CONSTRAINT df_profile_field_visibility_updated_at DEFAULT (CURRENT_TIMESTAMP), -- Last preference change.
        row_version bigint NOT NULL DEFAULT 1, -- Concurrency token.
        CONSTRAINT pk_profile_field_visibility_ PRIMARY KEY (member_id, field_code)
    );
-- core.member_verification: Administrator/member verification workflow.
CREATE TABLE IF NOT EXISTS core.member_verification (
        verification_id varchar(64) NOT NULL, -- Case identifier.
        member_id varchar(64) NOT NULL, -- FK iam.member.
        verification_type varchar(32) NOT NULL, -- EMAIL, PHONE, ORGANIZATION or MANUAL.
        status varchar(24) NOT NULL CONSTRAINT df_member_verification_status DEFAULT ('PENDING'), -- PENDING, APPROVED, REJECTED, EXPIRED.
        evidence_file_asset_id varchar(64) NULL, -- Private storage.file_asset evidence reference, if policy permits.
        reviewed_by varchar(64) NULL, -- Administrator member ID.
        reviewed_at timestamptz NULL, -- Review completion.
        reason_code varchar(64) NULL, -- Controlled result reason.
        created_at timestamptz NOT NULL CONSTRAINT df_member_verification_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_member_verification_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_member_verification_ PRIMARY KEY (verification_id)
    );
-- consent.consent_policy: Versioned consent purpose and legal/community text.
CREATE TABLE IF NOT EXISTS consent.consent_policy (
        policy_id varchar(64) NOT NULL, -- Stable policy version ID.
        purpose_code varchar(64) NOT NULL, -- TERMS, LOCATION, LIVE_MODE, NOTIFICATIONS, ANALYTICS.
        version varchar(32) NOT NULL, -- Human-readable version.
        locale varchar(16) NOT NULL CONSTRAINT df_consent_policy_locale DEFAULT ('en'), -- Text locale.
        content_hash char(64) NOT NULL, -- SHA-256 of presented content.
        effective_from timestamptz NOT NULL, -- Activation time.
        retired_at timestamptz NULL, -- Retirement time.
        created_at timestamptz NOT NULL CONSTRAINT df_consent_policy_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_consent_policy_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_consent_policy_ PRIMARY KEY (policy_id)
    );
-- consent.member_consent: Authoritative grant/withdrawal evidence by purpose.
CREATE TABLE IF NOT EXISTS consent.member_consent (
        member_consent_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Evidence record.
        member_id varchar(64) NOT NULL, -- FK iam.member.
        policy_id varchar(64) NOT NULL, -- FK consent_policy.
        decision varchar(16) NOT NULL, -- GRANTED or DENIED.
        captured_at timestamptz NOT NULL CONSTRAINT df_member_consent_captured_at DEFAULT (CURRENT_TIMESTAMP), -- Decision time.
        withdrawn_at timestamptz NULL, -- Withdrawal time.
        capture_channel varchar(24) NOT NULL, -- MOBILE, WEB_ADMIN or SUPPORT.
        evidence_json jsonb NULL, -- Bounded device/app/version evidence; no secrets.
        CONSTRAINT pk_member_consent_ PRIMARY KEY (member_consent_id)
    );
-- consent.privacy_request: member data access, correction, deletion or consent-support case.
CREATE TABLE IF NOT EXISTS consent.privacy_request (
        privacy_request_id varchar(64) NOT NULL, -- Case identifier.
        member_id varchar(64) NOT NULL, -- Requesting member.
        request_type varchar(24) NOT NULL, -- ACCESS, CORRECT, DELETE, EXPORT, CONSENT_SUPPORT.
        status varchar(24) NOT NULL CONSTRAINT df_privacy_request_status DEFAULT ('OPEN'), -- OPEN, VERIFIED, PROCESSING, COMPLETED, REJECTED.
        verified_at timestamptz NULL, -- Identity verification.
        due_at timestamptz NULL, -- Policy deadline.
        completed_at timestamptz NULL, -- Completion time.
        result_file_asset_id varchar(64) NULL, -- Private storage.file_asset export package reference.
        created_at timestamptz NOT NULL CONSTRAINT df_privacy_request_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_privacy_request_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_privacy_request_ PRIMARY KEY (privacy_request_id)
    );
-- consent.privacy_request_task: Per-domain execution and evidence ledger for a privacy request.
CREATE TABLE IF NOT EXISTS consent.privacy_request_task (
        privacy_request_task_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Execution step identifier.
        privacy_request_id varchar(64) NOT NULL, -- FK consent.privacy_request.
        domain_code varchar(32) NOT NULL, -- IAM, PROFILE, EVENT, SOCIAL, CHAT, STORAGE, NLP, ANALYTICS or AUDIT.
        action_type varchar(24) NOT NULL, -- EXPORT, CORRECT, ANONYMIZE, DELETE or RETAIN_EXCEPTION.
        status varchar(20) NOT NULL CONSTRAINT df_privacy_request_task_status DEFAULT ('PENDING'), -- PENDING, RUNNING, COMPLETED, FAILED or EXEMPTED.
        attempt_count smallint NOT NULL CONSTRAINT df_privacy_request_task_attempt_count DEFAULT (0), -- Execution attempts.
        evidence_code varchar(64) NULL, -- Controlled completion or exception evidence.
        evidence_hash char(64) NULL, -- Hash of generated evidence or result manifest.
        started_at timestamptz NULL, -- First execution start.
        completed_at timestamptz NULL, -- Successful or exempted completion.
        last_error_code varchar(64) NULL, -- Sanitized retryable/permanent error.
        created_at timestamptz NOT NULL CONSTRAINT df_privacy_request_task_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_privacy_request_task_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_privacy_request_task_ PRIMARY KEY (privacy_request_task_id)
    );
-- event.venue: Admin-configured venue and coarse proximity boundary.
CREATE TABLE IF NOT EXISTS event.venue (
        venue_id varchar(64) NOT NULL, -- venue identifier.
        name varchar(200) NOT NULL, -- venue name.
        country_code char(2) NOT NULL, -- ISO country.
        region varchar(120) NULL, -- Region/state.
        city varchar(120) NULL, -- City.
        coarse_geo_cell varchar(32) NULL, -- venue-level geohash/H3 cell; not member location.
        timezone_id varchar(64) NOT NULL, -- IANA/Windows mapping controlled by service.
        created_at timestamptz NOT NULL CONSTRAINT df_venue_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_venue_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_venue_ PRIMARY KEY (venue_id)
    );
-- event.event: event/context used for registration, Live Mode and matching.
CREATE TABLE IF NOT EXISTS event.event (
        event_id varchar(64) NOT NULL, -- Also used as matching context_id.
        community_id varchar(64) NOT NULL, -- FK community.
        venue_id varchar(64) NULL, -- FK venue.
        name varchar(250) NOT NULL, -- event name.
        description varchar(2000) NULL, -- Admin-managed description.
        starts_at timestamptz NOT NULL, -- UTC start.
        ends_at timestamptz NOT NULL, -- UTC end.
        status varchar(24) NOT NULL CONSTRAINT df_event_status DEFAULT ('DRAFT'), -- DRAFT, PUBLISHED, ACTIVE, COMPLETED, CANCELLED.
        live_mode_enabled boolean NOT NULL CONSTRAINT df_event_live_mode_enabled DEFAULT (false), -- event allows Live Mode.
        created_at timestamptz NOT NULL CONSTRAINT df_event_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_event_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_event_ PRIMARY KEY (event_id)
    );
-- event.event_matching_policy: Versioned event-level eligibility, proximity, ranking and match-alert controls.
CREATE TABLE IF NOT EXISTS event.event_matching_policy (
        event_matching_policy_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Immutable policy version identifier.
        event_id varchar(64) NOT NULL, -- FK event; policy applies only to this event/context.
        policy_version smallint NOT NULL CONSTRAINT df_event_matching_policy_policy_version DEFAULT (1), -- Monotonic version within the event.
        status varchar(16) NOT NULL CONSTRAINT df_event_matching_policy_status DEFAULT ('DRAFT'), -- DRAFT, ACTIVE or RETIRED.
        registration_required boolean NOT NULL CONSTRAINT df_event_matching_policy_registration_required DEFAULT (true), -- member must hold an eligible event_registration.
        check_in_required boolean NOT NULL CONSTRAINT df_event_matching_policy_check_in_required DEFAULT (false), -- member must be checked in before event matching.
        live_mode_required boolean NOT NULL CONSTRAINT df_event_matching_policy_live_mode_required DEFAULT (true), -- Active consent-backed live_mode_session required.
        proximity_mode varchar(24) NOT NULL CONSTRAINT df_event_matching_policy_proximity_mode DEFAULT ('VENUE'), -- NONE, VENUE or COARSE_CELL.
        max_presence_age_minutes smallint NULL CONSTRAINT df_event_matching_policy_max_presence_age_minutes DEFAULT (15), -- Maximum age of coarse presence when proximity is used.
        match_threshold_override numeric(6,5) NULL, -- Optional override of active NLP ranking threshold.
        alert_confidence_threshold numeric(6,5) NOT NULL CONSTRAINT df_event_matching_policy_alert_confidence_threshold DEFAULT (0.70), -- Minimum final score before a proactive match alert is eligible.
        max_match_alerts_per_hour smallint NOT NULL CONSTRAINT df_event_matching_policy_max_match_alerts_per_hour DEFAULT (2), -- event-specific hourly cap per member.
        max_match_alerts_per_event smallint NOT NULL CONSTRAINT df_event_matching_policy_max_match_alerts_per_event DEFAULT (10), -- event-lifetime cap per member.
        minimum_alert_interval_minutes smallint NOT NULL CONSTRAINT df_event_matching_policy_minimum_alert_interval_minutes DEFAULT (30), -- Minimum spacing between event match alerts.
        effective_from timestamptz NOT NULL, -- Start of policy applicability.
        effective_to timestamptz NULL, -- Optional retirement time.
        created_at timestamptz NOT NULL CONSTRAINT df_event_matching_policy_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_event_matching_policy_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_event_matching_policy_ PRIMARY KEY (event_matching_policy_id)
    );
-- event.event_registration: member eligibility/check-in relationship to an event.
CREATE TABLE IF NOT EXISTS event.event_registration (
        event_registration_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Internal key.
        event_id varchar(64) NOT NULL, -- FK event.
        member_id varchar(64) NOT NULL, -- FK member.
        status varchar(24) NOT NULL CONSTRAINT df_event_registration_status DEFAULT ('REGISTERED'), -- INVITED, REGISTERED, CHECKED_IN, CANCELLED.
        registered_at timestamptz NOT NULL CONSTRAINT df_event_registration_registered_at DEFAULT (CURRENT_TIMESTAMP), -- Registration time.
        checked_in_at timestamptz NULL, -- event check-in time.
        source varchar(24) NOT NULL CONSTRAINT df_event_registration_source DEFAULT ('APP'), -- APP, ADMIN, IMPORT.
        created_at timestamptz NOT NULL CONSTRAINT df_event_registration_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_event_registration_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_event_registration_ PRIMARY KEY (event_registration_id)
    );
-- event.live_mode_session: Bounded, revocable member discovery session.
CREATE TABLE IF NOT EXISTS event.live_mode_session (
        live_session_id varchar(64) NOT NULL, -- Session identifier.
        event_id varchar(64) NOT NULL, -- FK event.
        member_id varchar(64) NOT NULL, -- FK member.
        consent_record_id bigint NOT NULL, -- Valid Live Mode consent evidence.
        status varchar(16) NOT NULL CONSTRAINT df_live_mode_session_status DEFAULT ('ACTIVE'), -- ACTIVE, DISABLED, EXPIRED.
        activated_at timestamptz NOT NULL CONSTRAINT df_live_mode_session_activated_at DEFAULT (CURRENT_TIMESTAMP), -- Activation time.
        active_until timestamptz NOT NULL, -- Hard expiry bounded by event.
        disabled_at timestamptz NULL, -- Immediate revocation time.
        created_at timestamptz NOT NULL CONSTRAINT df_live_mode_session_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_live_mode_session_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_live_mode_session_ PRIMARY KEY (live_session_id)
    );
-- event.event_presence: Coarse, short-lived evidence used for nearby matching.
CREATE TABLE IF NOT EXISTS event.event_presence (
        presence_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Internal key.
        live_session_id varchar(64) NOT NULL, -- FK live_mode_session.
        coarse_cell varchar(32) NOT NULL, -- Approved coarse geohash/H3 cell.
        observed_at timestamptz NOT NULL CONSTRAINT df_event_presence_observed_at DEFAULT (CURRENT_TIMESTAMP), -- Observation time.
        expires_at timestamptz NOT NULL, -- Automatic purge time.
        source varchar(24) NOT NULL, -- CHECK_IN, FOREGROUND_GEO or VENUE_ZONE.
        CONSTRAINT pk_event_presence_ PRIMARY KEY (presence_id)
    );
-- social.connection_request: Consent gate before creating a connection/chat.
CREATE TABLE IF NOT EXISTS social.connection_request (
        connection_request_id varchar(64) NOT NULL, -- Request identifier.
        sender_member_id varchar(64) NOT NULL, -- Requester.
        recipient_member_id varchar(64) NOT NULL, -- Recipient.
        context_id varchar(64) NULL, -- event or general matching context.
        match_result_id bigint NULL, -- Recommendation that led to request.
        note varchar(500) NULL, -- Optional introduction note; moderate as content.
        status varchar(24) NOT NULL CONSTRAINT df_connection_request_status DEFAULT ('PENDING'), -- PENDING, ACCEPTED, DECLINED, WITHDRAWN, EXPIRED.
        expires_at timestamptz NOT NULL, -- Policy-calculated expiry for a pending request.
        responded_at timestamptz NULL, -- Terminal response time.
        created_at timestamptz NOT NULL CONSTRAINT df_connection_request_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_connection_request_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_connection_request_ PRIMARY KEY (connection_request_id)
    );
-- social.connection: Mutually accepted member relationship.
CREATE TABLE IF NOT EXISTS social.connection (
        connection_id varchar(64) NOT NULL, -- connection identifier.
        member_low_id varchar(64) NOT NULL, -- Lexicographically lower member ID.
        member_high_id varchar(64) NOT NULL, -- Lexicographically higher member ID.
        accepted_request_id varchar(64) NOT NULL, -- Accepted connection_request.
        status varchar(20) NOT NULL CONSTRAINT df_connection_status DEFAULT ('ACTIVE'), -- ACTIVE or DISCONNECTED.
        connected_at timestamptz NOT NULL CONSTRAINT df_connection_connected_at DEFAULT (CURRENT_TIMESTAMP), -- Acceptance time.
        disconnected_at timestamptz NULL, -- Relationship end.
        created_at timestamptz NOT NULL CONSTRAINT df_connection_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_connection_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_connection_ PRIMARY KEY (connection_id)
    );
-- social.member_block: Directional block that suppresses discovery and communication both ways.
CREATE TABLE IF NOT EXISTS social.member_block (
        block_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Internal key.
        blocker_member_id varchar(64) NOT NULL, -- member initiating block.
        blocked_member_id varchar(64) NOT NULL, -- Blocked member.
        reason_code varchar(64) NULL, -- Private controlled reason.
        created_at timestamptz NOT NULL CONSTRAINT df_member_block_created_at DEFAULT (CURRENT_TIMESTAMP), -- Effective immediately.
        removed_at timestamptz NULL, -- Optional unblock.
        CONSTRAINT pk_member_block_ PRIMARY KEY (block_id)
    );
-- social.member_report: member-submitted safety/report workflow trigger.
CREATE TABLE IF NOT EXISTS social.member_report (
        report_id varchar(64) NOT NULL, -- Report identifier.
        reporter_member_id varchar(64) NOT NULL, -- Reporter.
        reported_member_id varchar(64) NOT NULL, -- Subject.
        resource_type varchar(32) NULL, -- PROFILE, REQUEST, MESSAGE, ATTACHMENT.
        resource_id varchar(64) NULL, -- Reported object.
        category varchar(64) NOT NULL, -- Controlled report category.
        description varchar(2000) NULL, -- Reporter description.
        status varchar(24) NOT NULL CONSTRAINT df_member_report_status DEFAULT ('OPEN'), -- OPEN, TRIAGED, RESOLVED, DISMISSED.
        created_at timestamptz NOT NULL CONSTRAINT df_member_report_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_member_report_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_member_report_ PRIMARY KEY (report_id)
    );
-- chat.conversation: Accepted-connection one-to-one chat container.
CREATE TABLE IF NOT EXISTS chat.conversation (
        conversation_id varchar(64) NOT NULL, -- conversation identifier.
        connection_id varchar(64) NOT NULL, -- One conversation per accepted connection.
        status varchar(20) NOT NULL CONSTRAINT df_conversation_status DEFAULT ('ACTIVE'), -- ACTIVE, CLOSED, RESTRICTED.
        last_message_at timestamptz NULL, -- conversation list ordering.
        created_at timestamptz NOT NULL CONSTRAINT df_conversation_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_conversation_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_conversation_ PRIMARY KEY (conversation_id)
    );
-- chat.conversation_participant: Per-member chat state and authorization projection.
CREATE TABLE IF NOT EXISTS chat.conversation_participant (
        conversation_id varchar(64) NOT NULL, -- FK conversation.
        member_id varchar(64) NOT NULL, -- Participant.
        joined_at timestamptz NOT NULL CONSTRAINT df_conversation_participant_joined_at DEFAULT (CURRENT_TIMESTAMP), -- Participation start.
        last_read_message_id varchar(64) NULL, -- Read cursor.
        muted_until timestamptz NULL, -- notification suppression.
        left_at timestamptz NULL, -- Closure/disconnect projection.
        CONSTRAINT pk_conversation_participant_ PRIMARY KEY (conversation_id, member_id)
    );
-- chat.message: Durable one-to-one message.
CREATE TABLE IF NOT EXISTS chat.message (
        message_id varchar(64) NOT NULL, -- Client-generated ID supports idempotency.
        conversation_id varchar(64) NOT NULL, -- FK conversation.
        sender_member_id varchar(64) NOT NULL, -- Authorized participant.
        message_type varchar(20) NOT NULL CONSTRAINT df_message_message_type DEFAULT ('TEXT'), -- TEXT, FILE, SYSTEM.
        body text NULL, -- Text content; sanitize for display.
        client_sent_at timestamptz NULL, -- Client timestamp for UX only.
        server_sequence bigint NOT NULL CONSTRAINT df_message_server_sequence DEFAULT (nextval('chat.message_sequence')), -- Monotonic per conversation or global stream.
        moderation_status varchar(24) NOT NULL CONSTRAINT df_message_moderation_status DEFAULT ('PENDING_OR_CLEAR'), -- Safety state.
        deleted_at timestamptz NULL, -- Logical removal time.
        created_at timestamptz NOT NULL CONSTRAINT df_message_created_at DEFAULT (CURRENT_TIMESTAMP), -- Authoritative send time.
        row_version bigint NOT NULL DEFAULT 1, -- Concurrency token.
        CONSTRAINT pk_message_ PRIMARY KEY (message_id)
    );
-- chat.message_receipt: message delivered/read evidence by participant.
CREATE TABLE IF NOT EXISTS chat.message_receipt (
        message_id varchar(64) NOT NULL, -- FK message.
        member_id varchar(64) NOT NULL, -- Recipient participant.
        delivered_at timestamptz NULL, -- First delivery.
        read_at timestamptz NULL, -- First read.
        updated_at timestamptz NOT NULL CONSTRAINT df_message_receipt_updated_at DEFAULT (CURRENT_TIMESTAMP), -- Last receipt update.
        CONSTRAINT pk_message_receipt_ PRIMARY KEY (message_id, member_id)
    );
-- storage.file_asset: Domain-neutral metadata and security lifecycle for a private Azure Blob object.
CREATE TABLE IF NOT EXISTS storage.file_asset (
        file_asset_id varchar(64) NOT NULL, -- Opaque file identifier.
        community_id varchar(64) NOT NULL, -- FK core.community and authorization boundary.
        owner_member_id varchar(64) NULL, -- Uploader/owner when the asset belongs to a member.
        purpose_code varchar(32) NOT NULL, -- CHAT_FILE, VERIFICATION_EVIDENCE, PRIVACY_EXPORT or EVALUATION_REPORT.
        container_name varchar(128) NOT NULL, -- Allowlisted private container; not client supplied.
        blob_path varchar(1024) NOT NULL, -- Private blob path; never store a SAS URL.
        blob_path_hash char(64) NOT NULL, -- Deterministic lookup without broad path exposure.
        file_name varchar(255) NOT NULL, -- Sanitized display name.
        media_type varchar(128) NOT NULL, -- Verified MIME type.
        size_bytes bigint NOT NULL, -- Validated size.
        sha256 char(64) NOT NULL, -- Integrity and deduplication hash.
        classification varchar(24) NOT NULL CONSTRAINT df_file_asset_classification DEFAULT ('CONFIDENTIAL'), -- INTERNAL, CONFIDENTIAL, RESTRICTED or HIGHLY_RESTRICTED.
        scan_status varchar(24) NOT NULL CONSTRAINT df_file_asset_scan_status DEFAULT ('PENDING'), -- PENDING, CLEAN, REJECTED or ERROR.
        lifecycle_status varchar(20) NOT NULL CONSTRAINT df_file_asset_lifecycle_status DEFAULT ('UPLOADING'), -- UPLOADING, AVAILABLE, QUARANTINED, DELETED or EXPIRED.
        expires_at timestamptz NULL, -- Purpose policy or orphan-upload purge time.
        deleted_at timestamptz NULL, -- Deletion completion time.
        created_at timestamptz NOT NULL CONSTRAINT df_file_asset_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_file_asset_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_file_asset_ PRIMARY KEY (file_asset_id)
    );
-- storage.file_asset_link: Association between a file_asset and an authorized product resource.
CREATE TABLE IF NOT EXISTS storage.file_asset_link (
        file_asset_link_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Association identifier.
        file_asset_id varchar(64) NOT NULL, -- FK storage.file_asset.
        resource_type varchar(32) NOT NULL, -- MESSAGE, MEMBER_VERIFICATION, PRIVACY_REQUEST or EVALUATION_RUN.
        resource_id varchar(64) NOT NULL, -- Authorized domain resource identifier.
        relationship_type varchar(32) NOT NULL CONSTRAINT df_file_asset_link_relationship_type DEFAULT ('PRIMARY'), -- PRIMARY, EVIDENCE, RESULT or REPORT.
        linked_by varchar(64) NULL, -- member, administrator or service actor.
        created_at timestamptz NOT NULL CONSTRAINT df_file_asset_link_created_at DEFAULT (CURRENT_TIMESTAMP), -- Link creation time.
        removed_at timestamptz NULL, -- Logical unlink time.
        CONSTRAINT pk_file_asset_link_ PRIMARY KEY (file_asset_link_id)
    );
-- notification.notification_policy: Versioned channel, frequency, quiet-hours, retry and expiry controls by notification purpose.
CREATE TABLE IF NOT EXISTS notification.notification_policy (
        notification_policy_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Immutable policy version identifier.
        community_id varchar(64) NULL, -- Optional community scope; null is platform default.
        purpose_code varchar(64) NOT NULL, -- MATCH, REQUEST, CHAT, EVENT, SAFETY or ACCOUNT.
        channel varchar(16) NOT NULL, -- PUSH, EMAIL or IN_APP.
        policy_version smallint NOT NULL CONSTRAINT df_notification_policy_policy_version DEFAULT (1), -- Monotonic version for scope/purpose/channel.
        status varchar(16) NOT NULL CONSTRAINT df_notification_policy_status DEFAULT ('DRAFT'), -- DRAFT, ACTIVE or RETIRED.
        member_opt_out_allowed boolean NOT NULL CONSTRAINT df_notification_policy_member_opt_out_allowed DEFAULT (true), -- Whether member preference may disable this notification.
        quiet_hours_behavior varchar(16) NOT NULL CONSTRAINT df_notification_policy_quiet_hours_behavior DEFAULT ('DEFER'), -- DEFER, SUPPRESS or BYPASS.
        dedupe_window_seconds int NOT NULL CONSTRAINT df_notification_policy_dedupe_window_seconds DEFAULT (300), -- Duplicate suppression window for the same dedupe key.
        max_per_hour smallint NOT NULL CONSTRAINT df_notification_policy_max_per_hour DEFAULT (6), -- Maximum queued/sent notifications per member and policy each hour.
        max_per_day smallint NOT NULL CONSTRAINT df_notification_policy_max_per_day DEFAULT (30), -- Maximum queued/sent notifications per member and policy each day.
        max_attempts smallint NOT NULL CONSTRAINT df_notification_policy_max_attempts DEFAULT (3), -- Bounded provider delivery attempts.
        retry_schedule_seconds varchar(128) NOT NULL CONSTRAINT df_notification_policy_retry_schedule_seconds DEFAULT ('60,300,1800'), -- Validated comma-separated retry delays.
        ttl_minutes int NOT NULL CONSTRAINT df_notification_policy_ttl_minutes DEFAULT (1440), -- notification expiry after initial eligibility.
        effective_from timestamptz NOT NULL, -- Start of policy applicability.
        effective_to timestamptz NULL, -- Optional retirement time.
        created_at timestamptz NOT NULL CONSTRAINT df_notification_policy_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_notification_policy_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_notification_policy_ PRIMARY KEY (notification_policy_id)
    );
-- notification.notification_preference: member channel, quiet hours and purpose preferences.
CREATE TABLE IF NOT EXISTS notification.notification_preference (
        member_id varchar(64) NOT NULL, -- FK member.
        purpose_code varchar(64) NOT NULL, -- MATCH, REQUEST, CHAT, EVENT, SAFETY or ACCOUNT.
        push_enabled boolean NOT NULL CONSTRAINT df_notification_preference_push_enabled DEFAULT (true), -- Push channel preference.
        email_enabled boolean NOT NULL CONSTRAINT df_notification_preference_email_enabled DEFAULT (false), -- Email channel preference.
        quiet_start_local time NULL, -- Optional local quiet start.
        quiet_end_local time NULL, -- Optional local quiet end.
        timezone_id varchar(64) NULL, -- Required when quiet hours set.
        created_at timestamptz NOT NULL CONSTRAINT df_notification_preference_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_notification_preference_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_notification_preference_ PRIMARY KEY (member_id, purpose_code)
    );
-- notification.push_token: Provider push token mapped to a registered device.
CREATE TABLE IF NOT EXISTS notification.push_token (
        push_token_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Internal key.
        device_id varchar(64) NOT NULL, -- FK member_device.
        provider varchar(24) NOT NULL, -- APNS or FCM.
        token_ciphertext bytea NOT NULL, -- Encrypted/tokenized push token.
        status varchar(16) NOT NULL CONSTRAINT df_push_token_status DEFAULT ('ACTIVE'), -- ACTIVE or INVALID.
        last_success_at timestamptz NULL, -- Last accepted delivery.
        invalidated_at timestamptz NULL, -- Provider rejection/revocation.
        created_at timestamptz NOT NULL CONSTRAINT df_push_token_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_push_token_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        token_fingerprint char(64) NOT NULL, -- Stable SHA-256 fingerprint supplied by the service for uniqueness without indexing ciphertext.
        CONSTRAINT pk_push_token_ PRIMARY KEY (push_token_id)
    );
-- notification.notification: Policy-resolved, rate-limited delivery intent and aggregate outcome.
CREATE TABLE IF NOT EXISTS notification.notification (
        notification_id varchar(64) NOT NULL, -- Delivery identifier.
        member_id varchar(64) NOT NULL, -- Recipient.
        notification_policy_id bigint NOT NULL, -- Immutable notification_policy version applied.
        event_matching_policy_id bigint NULL, -- event_matching_policy applied to an event match alert.
        purpose_code varchar(64) NOT NULL, -- notification purpose.
        channel varchar(16) NOT NULL, -- Resolved PUSH, EMAIL or IN_APP channel.
        resource_type varchar(32) NULL, -- MATCH, REQUEST, MESSAGE, EVENT.
        resource_id varchar(64) NULL, -- Deep-link resource.
        template_code varchar(64) NOT NULL, -- Versioned content template.
        dedupe_key varchar(160) NOT NULL, -- Stable purpose/member/resource key used for duplicate suppression.
        dedupe_bucket_start timestamptz NOT NULL, -- Start of the policy-derived deduplication window.
        source_confidence numeric(6,5) NULL, -- Match confidence captured when threshold-based notification is used.
        context_id varchar(64) NULL, -- event ID or GENERAL context used for event-lifetime caps.
        status varchar(20) NOT NULL CONSTRAINT df_notification_status DEFAULT ('PENDING'), -- PENDING, SENT, DELIVERED, FAILED, SUPPRESSED.
        scheduled_at timestamptz NOT NULL CONSTRAINT df_notification_scheduled_at DEFAULT (CURRENT_TIMESTAMP), -- Quiet-hours-aware schedule.
        expires_at timestamptz NOT NULL, -- Policy-calculated time after which delivery is suppressed.
        attempt_count smallint NOT NULL CONSTRAINT df_notification_attempt_count DEFAULT (0), -- Aggregate count of append-only delivery attempts.
        sent_at timestamptz NULL, -- Provider acceptance time.
        delivered_at timestamptz NULL, -- Provider delivery acknowledgment when available.
        suppression_reason varchar(64) NULL, -- OPT_OUT, QUIET_HOURS, RATE_LIMIT, DUPLICATE, EXPIRED, BELOW_THRESHOLD or POLICY.
        failure_code varchar(64) NULL, -- Sanitized provider failure.
        created_at timestamptz NOT NULL CONSTRAINT df_notification_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_notification_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_notification_ PRIMARY KEY (notification_id)
    );
-- notification.notification_delivery_attempt: Append-only provider attempt and acknowledgment history.
CREATE TABLE IF NOT EXISTS notification.notification_delivery_attempt (
        delivery_attempt_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Attempt identifier.
        notification_id varchar(64) NOT NULL, -- FK notification.
        attempt_number smallint NOT NULL, -- One-based attempt number.
        provider varchar(32) NOT NULL, -- APNS, FCM, EMAIL_PROVIDER or IN_APP.
        push_token_id bigint NULL, -- push_token used; null for non-push channels.
        provider_message_id varchar(256) NULL, -- Provider correlation ID; never a credential.
        status varchar(20) NOT NULL CONSTRAINT df_notification_delivery_attempt_status DEFAULT ('STARTED'), -- STARTED, ACCEPTED, DELIVERED, FAILED or EXPIRED.
        attempted_at timestamptz NOT NULL CONSTRAINT df_notification_delivery_attempt_attempted_at DEFAULT (CURRENT_TIMESTAMP), -- Attempt start time.
        acknowledged_at timestamptz NULL, -- Provider acknowledgment time.
        next_attempt_at timestamptz NULL, -- Next policy-derived retry time.
        duration_ms int NULL, -- Provider request duration.
        failure_code varchar(64) NULL, -- Sanitized failure category.
        CONSTRAINT pk_notification_delivery_attempt_ PRIMARY KEY (delivery_attempt_id)
    );
-- nlp.nlp_intent: Current WANT/OFFER text and structured matching metadata.
CREATE TABLE IF NOT EXISTS nlp.nlp_intent (
        intent_id varchar(64) NOT NULL, -- Matches existing API contract.
        member_id varchar(64) NOT NULL, -- Authoritative FK iam.member.
        context_id varchar(64) NOT NULL, -- event ID or GENERAL context.
        intent_type varchar(16) NOT NULL, -- WANT or OFFER.
        original_text varchar(4000) NOT NULL, -- member-authored display text.
        normalized_text varchar(4000) NOT NULL, -- PII-minimized normalization.
        normalized_hash char(64) NOT NULL, -- Content hash for idempotent embedding.
        language_code varchar(16) NOT NULL CONSTRAINT df_nlp_intent_language_code DEFAULT ('en'), -- Detected/approved language.
        contains_pii boolean NOT NULL CONSTRAINT df_nlp_intent_contains_pii DEFAULT (false), -- Preprocessing signal.
        status varchar(32) NOT NULL CONSTRAINT df_nlp_intent_status DEFAULT ('PROCESSING'), -- PROCESSING, MATCH_READY, FAILED, INACTIVE.
        category varchar(128) NULL, -- Structured category.
        industry varchar(128) NULL, -- Structured industry.
        geography varchar(128) NULL, -- Business geography, not live location.
        expires_at timestamptz NOT NULL, -- Freshness/eligibility expiry.
        preprocessing_version varchar(128) NOT NULL, -- Normalizer version.
        created_at timestamptz NOT NULL CONSTRAINT df_nlp_intent_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_nlp_intent_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_nlp_intent_ PRIMARY KEY (intent_id)
    );
-- nlp.nlp_embedding: Versioned vector for a normalized intent.
CREATE TABLE IF NOT EXISTS nlp.nlp_embedding (
        intent_id varchar(64) NOT NULL, -- FK nlp_intent.
        model_version varchar(128) NOT NULL, -- FK nlp_model_version.
        dimensions int NOT NULL, -- Vector dimensions.
        normalized_hash char(64) NOT NULL, -- Text version embedded.
        embedding vector(1536) NOT NULL, -- Exact cosine search remains bounded until HNSW is justified by load tests.
        status varchar(20) NOT NULL CONSTRAINT df_nlp_embedding_status DEFAULT ('ACTIVE'), -- ACTIVE, SUPERSEDED, FAILED.
        created_at timestamptz NOT NULL CONSTRAINT df_nlp_embedding_created_at DEFAULT (CURRENT_TIMESTAMP), -- Creation time.
        CONSTRAINT pk_nlp_embedding_ PRIMARY KEY (intent_id, model_version)
    );
-- nlp.nlp_model_version: Embedding provider/deployment and preprocessing compatibility.
CREATE TABLE IF NOT EXISTS nlp.nlp_model_version (
        model_version varchar(128) NOT NULL, -- Stable version.
        provider varchar(64) NOT NULL, -- Approved provider.
        deployment_name varchar(128) NOT NULL, -- Configuration reference, not secret.
        dimensions int NOT NULL, -- Expected vector length.
        preprocessing_version varchar(128) NOT NULL, -- Compatible preprocessing.
        status varchar(20) NOT NULL CONSTRAINT df_nlp_model_version_status DEFAULT ('CANDIDATE'), -- CANDIDATE, ACTIVE, RETIRED, ROLLED_BACK.
        activated_at timestamptz NULL, -- Promotion time.
        created_at timestamptz NOT NULL CONSTRAINT df_nlp_model_version_created_at DEFAULT (CURRENT_TIMESTAMP), -- Registration time.
        CONSTRAINT pk_nlp_model_version_ PRIMARY KEY (model_version)
    );
-- nlp.nlp_ranking_config: Versioned ranking weights, threshold and policy switches.
CREATE TABLE IF NOT EXISTS nlp.nlp_ranking_config (
        ranking_version varchar(128) NOT NULL, -- Stable configuration version.
        semantic_weight numeric(6,5) NOT NULL CONSTRAINT df_nlp_ranking_config_semantic_weight DEFAULT (0.40), -- Semantic/reciprocal weight.
        category_weight numeric(6,5) NOT NULL CONSTRAINT df_nlp_ranking_config_category_weight DEFAULT (0.25), -- Category compatibility.
        industry_weight numeric(6,5) NOT NULL CONSTRAINT df_nlp_ranking_config_industry_weight DEFAULT (0.15), -- Industry compatibility.
        geography_weight numeric(6,5) NOT NULL CONSTRAINT df_nlp_ranking_config_geography_weight DEFAULT (0.10), -- Business geography fit.
        freshness_weight numeric(6,5) NOT NULL CONSTRAINT df_nlp_ranking_config_freshness_weight DEFAULT (0.10), -- Intent freshness.
        event_weight numeric(6,5) NOT NULL CONSTRAINT df_nlp_ranking_config_event_weight DEFAULT (0), -- Optional event context after evaluation.
        threshold numeric(6,5) NOT NULL CONSTRAINT df_nlp_ranking_config_threshold DEFAULT (0.35), -- Display threshold.
        active_from timestamptz NOT NULL, -- Effective time.
        active_to timestamptz NULL, -- Retirement time.
        config_json jsonb NULL, -- Bounded extra rule settings.
        CONSTRAINT pk_nlp_ranking_config_ PRIMARY KEY (ranking_version)
    );
-- nlp.nlp_processing_job: Intent embedding and re-embedding retry state.
CREATE TABLE IF NOT EXISTS nlp.nlp_processing_job (
        job_id varchar(64) NOT NULL, -- Job identifier.
        intent_id varchar(64) NOT NULL, -- Target intent.
        job_type varchar(24) NOT NULL CONSTRAINT df_nlp_processing_job_job_type DEFAULT ('EMBED'), -- EMBED or REEMBED. Normalization is synchronous for MVP.
        status varchar(20) NOT NULL CONSTRAINT df_nlp_processing_job_status DEFAULT ('PENDING'), -- PENDING, RUNNING, SUCCEEDED, FAILED, DEAD.
        attempt_count int NOT NULL CONSTRAINT df_nlp_processing_job_attempt_count DEFAULT (0), -- Bounded attempts.
        available_at timestamptz NOT NULL CONSTRAINT df_nlp_processing_job_available_at DEFAULT (CURRENT_TIMESTAMP), -- Retry schedule.
        locked_until timestamptz NULL, -- Worker lease.
        error_code varchar(64) NULL, -- Sanitized failure code.
        created_at timestamptz NOT NULL CONSTRAINT df_nlp_processing_job_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_nlp_processing_job_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_nlp_processing_job_ PRIMARY KEY (job_id)
    );
-- nlp.match_request: Idempotent match-search execution envelope.
CREATE TABLE IF NOT EXISTS nlp.match_request (
        request_id varchar(64) NOT NULL, -- Client/API idempotency key.
        request_hash char(64) NOT NULL, -- Canonical hash of matching inputs; detects idempotency-key reuse with different inputs.
        requester_id varchar(64) NOT NULL, -- Authenticated member.
        intent_id varchar(64) NOT NULL, -- Requester intent.
        context_id varchar(64) NOT NULL, -- Matching context.
        language_code varchar(16) NOT NULL CONSTRAINT df_match_request_language_code DEFAULT ('en'), -- Language snapshot used for this request.
        requested_limit smallint NOT NULL CONSTRAINT df_match_request_requested_limit DEFAULT (7), -- Allowed 3-7.
        request_options_json jsonb NULL, -- Validated bounded options snapshot; no free-form secrets or raw provider payloads.
        status varchar(20) NOT NULL CONSTRAINT df_match_request_status DEFAULT ('PROCESSING'), -- PROCESSING, COMPLETED, FAILED.
        preprocessing_version varchar(128) NULL, -- Resolved synchronous normalization version.
        model_version varchar(128) NULL, -- Resolved model version.
        ranking_version varchar(128) NULL, -- Resolved ranking version.
        ranking_threshold numeric(6,5) NULL, -- Immutable threshold snapshot applied to this execution.
        candidate_count int NULL, -- Eligible bounded candidates examined.
        completed_at timestamptz NULL, -- Completion time.
        created_at timestamptz NOT NULL CONSTRAINT df_match_request_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_match_request_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_match_request_ PRIMARY KEY (request_id)
    );
-- nlp.nlp_match_result: Ranked, explained recommendation returned for one request.
CREATE TABLE IF NOT EXISTS nlp.nlp_match_result (
        match_result_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Internal key.
        request_id varchar(64) NOT NULL, -- FK match_request.
        requester_id varchar(64) NOT NULL, -- Requester.
        candidate_id varchar(64) NOT NULL, -- Candidate.
        rank smallint NOT NULL, -- 1-based result rank.
        semantic_score numeric(8,7) NOT NULL, -- Semantic score.
        reciprocal_score numeric(8,7) NULL, -- Bidirectional harmonic/approved score.
        final_score numeric(8,7) NOT NULL, -- Versioned final ranking score.
        label varchar(32) NOT NULL, -- STRONG_MATCH, PLAUSIBLE_MATCH, etc.
        reason_codes jsonb NOT NULL, -- JSON array of approved codes.
        reason_text varchar(2000) NOT NULL, -- Deterministic explanation.
        model_version varchar(128) NOT NULL, -- Embedding version.
        preprocessing_version varchar(128) NOT NULL, -- Normalization version.
        ranking_version varchar(128) NOT NULL, -- Ranking configuration.
        policy_status varchar(24) NOT NULL CONSTRAINT df_nlp_match_result_policy_status DEFAULT ('ELIGIBLE'), -- ELIGIBLE or SUPPRESSED.
        created_at timestamptz NOT NULL CONSTRAINT df_nlp_match_result_created_at DEFAULT (CURRENT_TIMESTAMP), -- Creation time.
        CONSTRAINT pk_nlp_match_result_ PRIMARY KEY (match_result_id)
    );
-- nlp.nlp_feedback: Useful/not useful/inappropriate signal for recommendation quality.
CREATE TABLE IF NOT EXISTS nlp.nlp_feedback (
        feedback_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Internal key.
        supersedes_feedback_id bigint NULL, -- Optional self-FK to the earlier feedback corrected by this row.
        match_result_id bigint NOT NULL, -- FK nlp_match_result.
        request_id varchar(64) NOT NULL, -- Denormalized request for compatibility.
        requester_id varchar(64) NOT NULL, -- Authenticated feedback author.
        candidate_id varchar(64) NOT NULL, -- Candidate.
        label varchar(64) NOT NULL, -- USEFUL, NOT_USEFUL, INAPPROPRIATE.
        reason_code varchar(64) NULL, -- Controlled error category.
        reason varchar(1000) NULL, -- Optional free text, PII checked.
        created_at timestamptz NOT NULL CONSTRAINT df_nlp_feedback_created_at DEFAULT (CURRENT_TIMESTAMP), -- Feedback time.
        CONSTRAINT pk_nlp_feedback_ PRIMARY KEY (feedback_id)
    );
-- nlp.match_suppression: Administrative or safety suppression independent of model score.
CREATE TABLE IF NOT EXISTS nlp.match_suppression (
        suppression_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Internal key.
        member_id varchar(64) NULL, -- Affected member.
        intent_id varchar(64) NULL, -- Affected intent.
        context_id varchar(64) NULL, -- Optional context.
        reason_code varchar(64) NOT NULL, -- Controlled reason.
        starts_at timestamptz NOT NULL CONSTRAINT df_match_suppression_starts_at DEFAULT (CURRENT_TIMESTAMP), -- Effective time.
        ends_at timestamptz NULL, -- Optional expiry.
        created_by varchar(64) NOT NULL, -- Administrator/service actor.
        CONSTRAINT pk_match_suppression_ PRIMARY KEY (suppression_id)
    );
-- nlp.evaluation_dataset: Versioned labelled-pair dataset metadata.
CREATE TABLE IF NOT EXISTS nlp.evaluation_dataset (
        dataset_id varchar(64) NOT NULL, -- Dataset version ID.
        name varchar(200) NOT NULL, -- Display name.
        version varchar(32) NOT NULL, -- Immutable version.
        description varchar(1000) NULL, -- Sampling/labeling notes.
        source_policy varchar(500) NOT NULL, -- De-identification/provenance statement.
        status varchar(20) NOT NULL CONSTRAINT df_evaluation_dataset_status DEFAULT ('DRAFT'), -- DRAFT, APPROVED, RETIRED.
        approved_by varchar(64) NULL, -- Evaluator/admin.
        created_at timestamptz NOT NULL CONSTRAINT df_evaluation_dataset_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_evaluation_dataset_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_evaluation_dataset_ PRIMARY KEY (dataset_id)
    );
-- nlp.evaluation_pair: One labelled reciprocal matching example.
CREATE TABLE IF NOT EXISTS nlp.evaluation_pair (
        evaluation_pair_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Pair identifier.
        dataset_id varchar(64) NOT NULL, -- FK evaluation_dataset.
        requester_intent_text varchar(4000) NOT NULL, -- De-identified requester sample.
        candidate_intent_text varchar(4000) NOT NULL, -- De-identified candidate sample.
        structured_features_json jsonb NULL, -- Category/industry/geography features.
        gold_label varchar(32) NOT NULL, -- STRONG, PLAUSIBLE, WEAK, NONE, UNSAFE.
        split varchar(16) NOT NULL, -- TRAIN, VALIDATION or TEST.
        organization_group varchar(64) NULL, -- Leakage-prevention grouping, pseudonymous.
        label_reason varchar(1000) NULL, -- Evaluator rationale.
        CONSTRAINT pk_evaluation_pair_ PRIMARY KEY (evaluation_pair_id)
    );
-- nlp.evaluation_run: Reproducible quality evaluation output.
CREATE TABLE IF NOT EXISTS nlp.evaluation_run (
        evaluation_run_id varchar(64) NOT NULL, -- Run identifier.
        dataset_id varchar(64) NOT NULL, -- Dataset version.
        model_version varchar(128) NOT NULL, -- Model under test.
        ranking_version varchar(128) NOT NULL, -- Ranking config.
        status varchar(20) NOT NULL CONSTRAINT df_evaluation_run_status DEFAULT ('RUNNING'), -- RUNNING, PASSED, FAILED, ERROR.
        metrics_json jsonb NULL, -- Precision@5, Recall@20, reciprocal precision, coverage.
        error_report_blob_path varchar(1024) NULL, -- Private report artifact.
        started_at timestamptz NOT NULL CONSTRAINT df_evaluation_run_started_at DEFAULT (CURRENT_TIMESTAMP), -- Run start.
        completed_at timestamptz NULL, -- Run completion.
        CONSTRAINT pk_evaluation_run_ PRIMARY KEY (evaluation_run_id)
    );
-- moderation.moderation_case: Unified case for member reports, content flags and account review.
CREATE TABLE IF NOT EXISTS moderation.moderation_case (
        moderation_case_id varchar(64) NOT NULL, -- Case identifier.
        source_type varchar(32) NOT NULL, -- MEMBER_REPORT, AUTO_SCAN, ADMIN_REVIEW.
        source_id varchar(64) NULL, -- Source record identifier.
        subject_member_id varchar(64) NULL, -- member under review.
        resource_type varchar(32) NULL, -- PROFILE, MESSAGE, ATTACHMENT, INTENT.
        resource_id varchar(64) NULL, -- Reviewed resource.
        priority varchar(16) NOT NULL CONSTRAINT df_moderation_case_priority DEFAULT ('NORMAL'), -- LOW, NORMAL, HIGH, URGENT.
        status varchar(24) NOT NULL CONSTRAINT df_moderation_case_status DEFAULT ('OPEN'), -- OPEN, TRIAGED, ACTIONED, CLOSED.
        assigned_to varchar(64) NULL, -- Moderator.
        closed_at timestamptz NULL, -- Closure time.
        created_at timestamptz NOT NULL CONSTRAINT df_moderation_case_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_moderation_case_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_moderation_case_ PRIMARY KEY (moderation_case_id)
    );
-- moderation.moderation_action: Append-only action taken within a moderation case.
CREATE TABLE IF NOT EXISTS moderation.moderation_action (
        moderation_action_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Action identifier.
        moderation_case_id varchar(64) NOT NULL, -- FK moderation_case.
        actor_member_id varchar(64) NOT NULL, -- Moderator/admin.
        action_type varchar(64) NOT NULL, -- WARN, HIDE, SUSPEND, REJECT_FILE, CLOSE, etc.
        reason_code varchar(64) NOT NULL, -- Controlled reason.
        notes varchar(2000) NULL, -- Restricted case notes.
        effective_until timestamptz NULL, -- Temporary action expiry.
        created_at timestamptz NOT NULL CONSTRAINT df_moderation_action_created_at DEFAULT (CURRENT_TIMESTAMP), -- Action time.
        CONSTRAINT pk_moderation_action_ PRIMARY KEY (moderation_action_id)
    );
-- moderation.content_rule: Versioned blocked-content and moderation configuration.
CREATE TABLE IF NOT EXISTS moderation.content_rule (
        content_rule_id varchar(64) NOT NULL, -- Rule ID.
        rule_type varchar(32) NOT NULL, -- FILE_TYPE, TERM, RATE, POLICY.
        version varchar(32) NOT NULL, -- Rule version.
        config_json jsonb NOT NULL, -- Validated rule configuration.
        status varchar(16) NOT NULL CONSTRAINT df_content_rule_status DEFAULT ('DRAFT'), -- DRAFT, ACTIVE, RETIRED.
        active_from timestamptz NULL, -- Activation time.
        created_by varchar(64) NOT NULL, -- Administrator.
        created_at timestamptz NOT NULL CONSTRAINT df_content_rule_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_content_rule_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_content_rule_ PRIMARY KEY (content_rule_id)
    );
-- moderation.content_scan: Malware/content scan result for files or text resources.
CREATE TABLE IF NOT EXISTS moderation.content_scan (
        content_scan_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Scan record.
        resource_type varchar(32) NOT NULL, -- FILE_ASSET, PROFILE, INTENT or MESSAGE.
        resource_id varchar(64) NOT NULL, -- Target object.
        scanner varchar(64) NOT NULL, -- Scanner/provider ID.
        scanner_version varchar(64) NULL, -- Engine/signature version.
        result varchar(24) NOT NULL, -- CLEAN, FLAGGED, MALICIOUS, ERROR.
        reason_codes jsonb NULL, -- Sanitized JSON reason codes.
        scanned_at timestamptz NOT NULL CONSTRAINT df_content_scan_scanned_at DEFAULT (CURRENT_TIMESTAMP), -- Scan time.
        CONSTRAINT pk_content_scan_ PRIMARY KEY (content_scan_id)
    );
-- ops.sync_change: Authorization-safe mobile delta feed and tombstone ledger.
CREATE TABLE IF NOT EXISTS ops.sync_change (
        sync_sequence bigint NOT NULL CONSTRAINT df_sync_change_sync_sequence DEFAULT (nextval('ops.sync_change_sequence')), -- Monotonic sync API cursor.
        community_id varchar(64) NOT NULL, -- FK core.community.
        member_scope_id varchar(64) NULL, -- Optional member-specific visibility scope.
        resource_type varchar(32) NOT NULL, -- PROFILE, MATCH, REQUEST, CONVERSATION, MESSAGE or NOTIFICATION.
        resource_id varchar(64) NOT NULL, -- Changed resource identifier.
        change_type varchar(16) NOT NULL, -- UPSERT or DELETE.
        resource_version bigint NULL, -- Source concurrency-version snapshot where available.
        payload_json jsonb NULL, -- Minimum authorization-safe read-model payload; null for protected tombstones.
        occurred_at timestamptz NOT NULL CONSTRAINT df_sync_change_occurred_at DEFAULT (CURRENT_TIMESTAMP), -- Authoritative change time.
        expires_at timestamptz NOT NULL, -- Earliest purge time.
        CONSTRAINT pk_sync_change_ PRIMARY KEY (sync_sequence)
    );
-- ops.retention_policy: Versioned retention and disposition rules for product data classes.
CREATE TABLE IF NOT EXISTS ops.retention_policy (
        retention_policy_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Immutable policy version identifier.
        resource_type varchar(64) NOT NULL, -- Governed product data class.
        policy_version smallint NOT NULL CONSTRAINT df_retention_policy_policy_version DEFAULT (1), -- Monotonic version per resource type.
        status varchar(16) NOT NULL CONSTRAINT df_retention_policy_status DEFAULT ('DRAFT'), -- DRAFT, ACTIVE or RETIRED.
        retention_days int NOT NULL, -- Approved retention duration.
        disposition_action varchar(20) NOT NULL, -- DELETE, ANONYMIZE or ARCHIVE.
        legal_hold_supported boolean NOT NULL CONSTRAINT df_retention_policy_legal_hold_supported DEFAULT (true), -- Whether disposition can be delayed by approved legal hold.
        effective_from timestamptz NOT NULL, -- Activation time.
        effective_to timestamptz NULL, -- Optional retirement time.
        approved_by varchar(64) NULL, -- Approving privacy/security administrator.
        created_at timestamptz NOT NULL CONSTRAINT df_retention_policy_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_retention_policy_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_retention_policy_ PRIMARY KEY (retention_policy_id)
    );
-- ops.retention_execution: Auditable execution result for one retention policy batch or resource.
CREATE TABLE IF NOT EXISTS ops.retention_execution (
        retention_execution_id varchar(64) NOT NULL, -- Execution identifier.
        retention_policy_id bigint NOT NULL, -- Immutable policy version applied.
        scope_start timestamptz NOT NULL, -- Inclusive evaluation window start.
        scope_end timestamptz NOT NULL, -- Exclusive evaluation window end.
        status varchar(20) NOT NULL CONSTRAINT df_retention_execution_status DEFAULT ('RUNNING'), -- RUNNING, SUCCEEDED, PARTIAL or FAILED.
        examined_count bigint NOT NULL CONSTRAINT df_retention_execution_examined_count DEFAULT (0), -- Rows/resources evaluated.
        disposed_count bigint NOT NULL CONSTRAINT df_retention_execution_disposed_count DEFAULT (0), -- Rows/resources disposed.
        skipped_hold_count bigint NOT NULL CONSTRAINT df_retention_execution_skipped_hold_count DEFAULT (0), -- Resources skipped due to legal hold.
        evidence_hash char(64) NULL, -- Hash of execution manifest/log evidence.
        started_at timestamptz NOT NULL CONSTRAINT df_retention_execution_started_at DEFAULT (CURRENT_TIMESTAMP), -- Execution start.
        completed_at timestamptz NULL, -- Terminal completion time.
        error_code varchar(64) NULL, -- Sanitized terminal error.
        CONSTRAINT pk_retention_execution_ PRIMARY KEY (retention_execution_id)
    );
-- ops.outbox_event: Transactional event publication without dual-write loss.
CREATE TABLE IF NOT EXISTS ops.outbox_event (
        outbox_event_id varchar(64) NOT NULL, -- event ID/idempotency token.
        aggregate_type varchar(64) NOT NULL, -- MEMBER, CONNECTION, MESSAGE, INTENT.
        aggregate_id varchar(64) NOT NULL, -- Source aggregate.
        event_type varchar(128) NOT NULL, -- Versioned event name.
        payload_json jsonb NOT NULL, -- Minimal event payload; avoid raw content.
        occurred_at timestamptz NOT NULL CONSTRAINT df_outbox_event_occurred_at DEFAULT (CURRENT_TIMESTAMP), -- Business event time.
        published_at timestamptz NULL, -- Successful publish time.
        attempt_count int NOT NULL CONSTRAINT df_outbox_event_attempt_count DEFAULT (0), -- Publish attempts.
        next_attempt_at timestamptz NULL, -- Retry schedule.
        CONSTRAINT pk_outbox_event_ PRIMARY KEY (outbox_event_id)
    );
-- ops.idempotency_record: Safe replay of mobile/API commands.
CREATE TABLE IF NOT EXISTS ops.idempotency_record (
        scope varchar(64) NOT NULL, -- API/operation scope.
        idempotency_key varchar(128) NOT NULL, -- Client key.
        actor_id varchar(64) NOT NULL, -- Authenticated member/service.
        request_hash char(64) NOT NULL, -- Detect key reuse with different body.
        status_code smallint NULL, -- Cached response status.
        response_ref varchar(1000) NULL, -- Bounded response or resource reference.
        created_at timestamptz NOT NULL CONSTRAINT df_idempotency_record_created_at DEFAULT (CURRENT_TIMESTAMP), -- First request.
        expires_at timestamptz NOT NULL, -- Purge time.
        CONSTRAINT pk_idempotency_record_ PRIMARY KEY (scope, idempotency_key)
    );
-- ops.background_job: Non-NLP background task lifecycle.
CREATE TABLE IF NOT EXISTS ops.background_job (
        background_job_id varchar(64) NOT NULL, -- Job ID.
        job_type varchar(64) NOT NULL, -- SCAN_FILE, SEND_NOTIFICATION, PURGE_PRESENCE, etc.
        resource_type varchar(32) NULL, -- Target type.
        resource_id varchar(64) NULL, -- Target ID.
        payload_json jsonb NULL, -- Minimal validated payload.
        status varchar(20) NOT NULL CONSTRAINT df_background_job_status DEFAULT ('PENDING'), -- PENDING, RUNNING, SUCCEEDED, FAILED, DEAD.
        attempt_count int NOT NULL CONSTRAINT df_background_job_attempt_count DEFAULT (0), -- Attempts.
        available_at timestamptz NOT NULL CONSTRAINT df_background_job_available_at DEFAULT (CURRENT_TIMESTAMP), -- Schedule/retry time.
        error_code varchar(64) NULL, -- Sanitized failure.
        created_at timestamptz NOT NULL CONSTRAINT df_background_job_created_at DEFAULT (CURRENT_TIMESTAMP), -- UTC creation time.
        updated_at timestamptz NOT NULL CONSTRAINT df_background_job_updated_at DEFAULT (CURRENT_TIMESTAMP), -- UTC last material update time.
        row_version bigint NOT NULL DEFAULT 1, -- Optimistic concurrency token; never client supplied.
        CONSTRAINT pk_background_job_ PRIMARY KEY (background_job_id)
    );
-- ops.audit_event: Append-only evidence of sensitive/security/admin actions.
CREATE TABLE IF NOT EXISTS ops.audit_event (
        audit_event_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Monotonic audit key.
        actor_type varchar(24) NOT NULL, -- MEMBER, ADMIN, SERVICE, SYSTEM.
        actor_id varchar(64) NULL, -- Pseudonymous/service identity.
        action varchar(128) NOT NULL, -- Versioned action code.
        resource_type varchar(64) NULL, -- Affected type.
        resource_id varchar(64) NULL, -- Affected ID.
        outcome varchar(16) NOT NULL, -- SUCCESS or DENIED/FAILED.
        correlation_id varchar(64) NOT NULL, -- End-to-end trace ID.
        metadata_json jsonb NULL, -- Allowlisted, content-free metadata.
        occurred_at timestamptz NOT NULL CONSTRAINT df_audit_event_occurred_at DEFAULT (CURRENT_TIMESTAMP), -- event time.
        CONSTRAINT pk_audit_event_ PRIMARY KEY (audit_event_id)
    );
-- analytics.product_event: Privacy-safe product funnel and match-quality analytics.
CREATE TABLE IF NOT EXISTS analytics.product_event (
        product_event_id varchar(64) NOT NULL, -- event ID.
        event_name varchar(128) NOT NULL, -- PROFILE_COMPLETED, MATCH_VIEWED, REQUEST_SENT, etc.
        member_pseudonym char(64) NULL, -- Environment-specific salted hash, not member_id.
        community_id varchar(64) NOT NULL, -- Aggregation boundary.
        context_type varchar(32) NULL, -- EVENT or GENERAL.
        context_id varchar(64) NULL, -- Allowed context reference.
        properties_json jsonb NULL, -- Allowlisted non-content dimensions.
        occurred_at timestamptz NOT NULL, -- Client/server event time.
        received_at timestamptz NOT NULL CONSTRAINT df_product_event_received_at DEFAULT (CURRENT_TIMESTAMP), -- Server receipt time.
        CONSTRAINT pk_product_event_ PRIMARY KEY (product_event_id)
    );

-- Shared optimistic-concurrency trigger; API clients never supply row_version.
DO $$
DECLARE target record;
BEGIN
    FOR target IN
        SELECT table_schema, table_name
        FROM information_schema.columns
        WHERE column_name = 'row_version'
          AND table_schema IN ('core','iam','consent','event','social','chat','storage','notification','nlp','moderation','ops')
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS set_row_version ON %I.%I', target.table_schema, target.table_name);
        EXECUTE format(
            'CREATE TRIGGER set_row_version BEFORE UPDATE ON %I.%I FOR EACH ROW EXECUTE FUNCTION ops.set_row_version()',
            target.table_schema, target.table_name
        );
    END LOOP;
END;
$$;
