SELECT ops.add_constraint_if_missing('iam', 'member', 'fk_member_community_id', $constraint$FOREIGN KEY (community_id) REFERENCES core.community (community_id)$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'member_identity', 'fk_member_identity_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'member_role', 'fk_member_role_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'member_role', 'fk_member_role_role_code', $constraint$FOREIGN KEY (role_code) REFERENCES iam.role (role_code)$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'member_role', 'fk_member_role_granted_by', $constraint$FOREIGN KEY (granted_by) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'member_device', 'fk_member_device_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'organization', 'fk_organization_community_id', $constraint$FOREIGN KEY (community_id) REFERENCES core.community (community_id)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'organization_member', 'fk_organization_member_organization_id', $constraint$FOREIGN KEY (organization_id) REFERENCES core.organization (organization_id)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'organization_member', 'fk_organization_member_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'member_profile', 'fk_member_profile_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'sector', 'fk_sector_parent_sector_code', $constraint$FOREIGN KEY (parent_sector_code) REFERENCES core.sector (sector_code)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'member_sector', 'fk_member_sector_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'member_sector', 'fk_member_sector_sector_code', $constraint$FOREIGN KEY (sector_code) REFERENCES core.sector (sector_code)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'member_geography', 'fk_member_geography_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'profile_field_visibility', 'fk_profile_field_visibility_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'member_verification', 'fk_member_verification_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'member_verification', 'fk_member_verification_evidence_file_asset_id', $constraint$FOREIGN KEY (evidence_file_asset_id) REFERENCES storage.file_asset (file_asset_id)$constraint$);
SELECT ops.add_constraint_if_missing('core', 'member_verification', 'fk_member_verification_reviewed_by', $constraint$FOREIGN KEY (reviewed_by) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('consent', 'member_consent', 'fk_member_consent_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('consent', 'member_consent', 'fk_member_consent_policy_id', $constraint$FOREIGN KEY (policy_id) REFERENCES consent.consent_policy (policy_id)$constraint$);
SELECT ops.add_constraint_if_missing('consent', 'privacy_request', 'fk_privacy_request_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('consent', 'privacy_request', 'fk_privacy_request_result_file_asset_id', $constraint$FOREIGN KEY (result_file_asset_id) REFERENCES storage.file_asset (file_asset_id)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event', 'fk_event_community_id', $constraint$FOREIGN KEY (community_id) REFERENCES core.community (community_id)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event', 'fk_event_venue_id', $constraint$FOREIGN KEY (venue_id) REFERENCES event.venue (venue_id)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event_matching_policy', 'fk_event_matching_policy_event_id', $constraint$FOREIGN KEY (event_id) REFERENCES event.event (event_id)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event_registration', 'fk_event_registration_event_id', $constraint$FOREIGN KEY (event_id) REFERENCES event.event (event_id)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event_registration', 'fk_event_registration_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'live_mode_session', 'fk_live_mode_session_event_id', $constraint$FOREIGN KEY (event_id) REFERENCES event.event (event_id)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'live_mode_session', 'fk_live_mode_session_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'live_mode_session', 'fk_live_mode_session_consent_record_id', $constraint$FOREIGN KEY (consent_record_id) REFERENCES consent.member_consent (member_consent_id)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event_presence', 'fk_event_presence_live_session_id', $constraint$FOREIGN KEY (live_session_id) REFERENCES event.live_mode_session (live_session_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'connection_request', 'fk_connection_request_sender_member_id', $constraint$FOREIGN KEY (sender_member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'connection_request', 'fk_connection_request_recipient_member_id', $constraint$FOREIGN KEY (recipient_member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'connection_request', 'fk_connection_request_match_result_id', $constraint$FOREIGN KEY (match_result_id) REFERENCES nlp.nlp_match_result (match_result_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'connection', 'fk_connection_member_low_id', $constraint$FOREIGN KEY (member_low_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'connection', 'fk_connection_member_high_id', $constraint$FOREIGN KEY (member_high_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'connection', 'fk_connection_accepted_request_id', $constraint$FOREIGN KEY (accepted_request_id) REFERENCES social.connection_request (connection_request_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'member_block', 'fk_member_block_blocker_member_id', $constraint$FOREIGN KEY (blocker_member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'member_block', 'fk_member_block_blocked_member_id', $constraint$FOREIGN KEY (blocked_member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'member_report', 'fk_member_report_reporter_member_id', $constraint$FOREIGN KEY (reporter_member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'member_report', 'fk_member_report_reported_member_id', $constraint$FOREIGN KEY (reported_member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'conversation', 'fk_conversation_connection_id', $constraint$FOREIGN KEY (connection_id) REFERENCES social.connection (connection_id)$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'conversation_participant', 'fk_conversation_participant_conversation_id', $constraint$FOREIGN KEY (conversation_id) REFERENCES chat.conversation (conversation_id)$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'conversation_participant', 'fk_conversation_participant_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'conversation_participant', 'fk_conversation_participant_last_read_message_id', $constraint$FOREIGN KEY (last_read_message_id) REFERENCES chat.message (message_id)$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'message', 'fk_message_conversation_id', $constraint$FOREIGN KEY (conversation_id) REFERENCES chat.conversation (conversation_id)$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'message', 'fk_message_sender_member_id', $constraint$FOREIGN KEY (sender_member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'message_receipt', 'fk_message_receipt_message_id', $constraint$FOREIGN KEY (message_id) REFERENCES chat.message (message_id)$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'message_receipt', 'fk_message_receipt_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification_policy', 'fk_notification_policy_community_id', $constraint$FOREIGN KEY (community_id) REFERENCES core.community (community_id)$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification_preference', 'fk_notification_preference_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'push_token', 'fk_push_token_device_id', $constraint$FOREIGN KEY (device_id) REFERENCES iam.member_device (device_id)$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification', 'fk_notification_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification', 'fk_notification_notification_policy_id', $constraint$FOREIGN KEY (notification_policy_id) REFERENCES notification.notification_policy (notification_policy_id)$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification', 'fk_notification_event_matching_policy_id', $constraint$FOREIGN KEY (event_matching_policy_id) REFERENCES event.event_matching_policy (event_matching_policy_id)$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification_delivery_attempt', 'fk_notification_delivery_attempt_notification_id', $constraint$FOREIGN KEY (notification_id) REFERENCES notification.notification (notification_id)$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification_delivery_attempt', 'fk_notification_delivery_attempt_push_token_id', $constraint$FOREIGN KEY (push_token_id) REFERENCES notification.push_token (push_token_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_intent', 'fk_nlp_intent_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_embedding', 'fk_nlp_embedding_intent_id', $constraint$FOREIGN KEY (intent_id) REFERENCES nlp.nlp_intent (intent_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_embedding', 'fk_nlp_embedding_model_version', $constraint$FOREIGN KEY (model_version) REFERENCES nlp.nlp_model_version (model_version)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_processing_job', 'fk_nlp_processing_job_intent_id', $constraint$FOREIGN KEY (intent_id) REFERENCES nlp.nlp_intent (intent_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'match_request', 'fk_match_request_requester_id', $constraint$FOREIGN KEY (requester_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'match_request', 'fk_match_request_intent_id', $constraint$FOREIGN KEY (intent_id) REFERENCES nlp.nlp_intent (intent_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'match_request', 'fk_match_request_model_version', $constraint$FOREIGN KEY (model_version) REFERENCES nlp.nlp_model_version (model_version)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'match_request', 'fk_match_request_ranking_version', $constraint$FOREIGN KEY (ranking_version) REFERENCES nlp.nlp_ranking_config (ranking_version)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_match_result', 'fk_nlp_match_result_request_id', $constraint$FOREIGN KEY (request_id) REFERENCES nlp.match_request (request_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_match_result', 'fk_nlp_match_result_requester_id', $constraint$FOREIGN KEY (requester_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_match_result', 'fk_nlp_match_result_candidate_id', $constraint$FOREIGN KEY (candidate_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_match_result', 'fk_nlp_match_result_model_version', $constraint$FOREIGN KEY (model_version) REFERENCES nlp.nlp_model_version (model_version)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_match_result', 'fk_nlp_match_result_ranking_version', $constraint$FOREIGN KEY (ranking_version) REFERENCES nlp.nlp_ranking_config (ranking_version)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_feedback', 'fk_nlp_feedback_supersedes_feedback_id', $constraint$FOREIGN KEY (supersedes_feedback_id) REFERENCES nlp.nlp_feedback (feedback_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_feedback', 'fk_nlp_feedback_match_result_id', $constraint$FOREIGN KEY (match_result_id) REFERENCES nlp.nlp_match_result (match_result_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_feedback', 'fk_nlp_feedback_request_id', $constraint$FOREIGN KEY (request_id) REFERENCES nlp.match_request (request_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_feedback', 'fk_nlp_feedback_requester_id', $constraint$FOREIGN KEY (requester_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_feedback', 'fk_nlp_feedback_candidate_id', $constraint$FOREIGN KEY (candidate_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'match_suppression', 'fk_match_suppression_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'match_suppression', 'fk_match_suppression_intent_id', $constraint$FOREIGN KEY (intent_id) REFERENCES nlp.nlp_intent (intent_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'evaluation_dataset', 'fk_evaluation_dataset_approved_by', $constraint$FOREIGN KEY (approved_by) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'evaluation_pair', 'fk_evaluation_pair_dataset_id', $constraint$FOREIGN KEY (dataset_id) REFERENCES nlp.evaluation_dataset (dataset_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'evaluation_run', 'fk_evaluation_run_dataset_id', $constraint$FOREIGN KEY (dataset_id) REFERENCES nlp.evaluation_dataset (dataset_id)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'evaluation_run', 'fk_evaluation_run_model_version', $constraint$FOREIGN KEY (model_version) REFERENCES nlp.nlp_model_version (model_version)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'evaluation_run', 'fk_evaluation_run_ranking_version', $constraint$FOREIGN KEY (ranking_version) REFERENCES nlp.nlp_ranking_config (ranking_version)$constraint$);
SELECT ops.add_constraint_if_missing('moderation', 'moderation_case', 'fk_moderation_case_subject_member_id', $constraint$FOREIGN KEY (subject_member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('moderation', 'moderation_case', 'fk_moderation_case_assigned_to', $constraint$FOREIGN KEY (assigned_to) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('moderation', 'moderation_action', 'fk_moderation_action_moderation_case_id', $constraint$FOREIGN KEY (moderation_case_id) REFERENCES moderation.moderation_case (moderation_case_id)$constraint$);
SELECT ops.add_constraint_if_missing('moderation', 'moderation_action', 'fk_moderation_action_actor_member_id', $constraint$FOREIGN KEY (actor_member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('analytics', 'product_event', 'fk_product_event_community_id', $constraint$FOREIGN KEY (community_id) REFERENCES core.community (community_id)$constraint$);

-- Scope idempotency keys by authenticated actor. The earlier two-column key was
-- unnecessarily global and could make unrelated members collide on the same client key.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'ops.idempotency_record'::regclass
          AND conname = 'pk_idempotency_record_'
          AND pg_get_constraintdef(oid) <> 'PRIMARY KEY (scope, actor_id, idempotency_key)'
    ) THEN
        ALTER TABLE ops.idempotency_record DROP CONSTRAINT pk_idempotency_record_;
        ALTER TABLE ops.idempotency_record
            ADD CONSTRAINT pk_idempotency_record_ PRIMARY KEY (scope, actor_id, idempotency_key);
    END IF;
END;
$$;

SELECT ops.add_constraint_if_missing('iam', 'member', 'ck_member_status', $constraint$CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','ANONYMIZED','DELETED'))$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'member_identity', 'ck_member_identity_status', $constraint$CHECK (status IN ('ACTIVE','REVOKED'))$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'member_identity', 'ck_member_identity_revocation', $constraint$CHECK ((status = 'REVOKED') = (revoked_at IS NOT NULL))$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'role', 'ck_role_status', $constraint$CHECK (status IN ('ACTIVE','RETIRED'))$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'member_device', 'ck_member_device_platform', $constraint$CHECK (platform IN ('IOS','ANDROID'))$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'member_device', 'ck_member_device_status', $constraint$CHECK (status IN ('ACTIVE','REVOKED'))$constraint$);
SELECT ops.add_constraint_if_missing('core', 'member_profile', 'ck_member_profile_profile_status', $constraint$CHECK (profile_status IN ('DRAFT','PENDING_REVIEW','ACTIVE','HIDDEN'))$constraint$);
SELECT ops.add_constraint_if_missing('core', 'member_profile', 'ck_member_profile_visibility', $constraint$CHECK (visibility IN ('PUBLIC','MEMBERS','CONNECTED','HIDDEN'))$constraint$);
SELECT ops.add_constraint_if_missing('consent', 'member_consent', 'ck_member_consent_decision', $constraint$CHECK (decision IN ('GRANTED','DENIED','WITHDRAWN'))$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event', 'ck_event_status', $constraint$CHECK (status IN ('DRAFT','PUBLISHED','ACTIVE','COMPLETED','CANCELLED'))$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event_matching_policy', 'ck_event_matching_policy_status', $constraint$CHECK (status IN ('DRAFT','ACTIVE','RETIRED'))$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event_matching_policy', 'ck_event_matching_policy_proximity_mode', $constraint$CHECK (proximity_mode IN ('NONE','VENUE','COARSE_CELL'))$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event_registration', 'ck_event_registration_status', $constraint$CHECK (status IN ('INVITED','REGISTERED','CHECKED_IN','CANCELLED'))$constraint$);
SELECT ops.add_constraint_if_missing('event', 'live_mode_session', 'ck_live_mode_session_status', $constraint$CHECK (status IN ('ACTIVE','DISABLED','EXPIRED'))$constraint$);
SELECT ops.add_constraint_if_missing('event', 'live_mode_session', 'ck_live_mode_session_dates', $constraint$CHECK (active_until > activated_at AND (disabled_at IS NULL OR disabled_at >= activated_at))$constraint$);
SELECT ops.add_constraint_if_missing('event', 'venue', 'ck_venue_status', $constraint$CHECK (status IN ('ACTIVE','RETIRED'))$constraint$);
SELECT ops.add_constraint_if_missing('social', 'connection_request', 'ck_connection_request_status', $constraint$CHECK (status IN ('PENDING','ACCEPTED','DECLINED','WITHDRAWN','EXPIRED'))$constraint$);
SELECT ops.add_constraint_if_missing('social', 'connection', 'ck_connection_status', $constraint$CHECK (status IN ('ACTIVE','DISCONNECTED'))$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'conversation', 'ck_conversation_status', $constraint$CHECK (status IN ('ACTIVE','CLOSED','RESTRICTED'))$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'message', 'ck_message_message_type', $constraint$CHECK (message_type IN ('TEXT','FILE','SYSTEM'))$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'conversation_participant', 'ck_conversation_participant_dates', $constraint$CHECK (left_at IS NULL OR left_at >= joined_at)$constraint$);
SELECT ops.add_constraint_if_missing('chat', 'message_receipt', 'ck_message_receipt_dates', $constraint$CHECK ((delivered_at IS NOT NULL OR read_at IS NOT NULL) AND (read_at IS NULL OR (delivered_at IS NOT NULL AND read_at >= delivered_at)))$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification_policy', 'ck_notification_policy_channel', $constraint$CHECK (channel IN ('PUSH','EMAIL','IN_APP'))$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification_policy', 'ck_notification_policy_status', $constraint$CHECK (status IN ('DRAFT','ACTIVE','RETIRED'))$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification_policy', 'ck_notification_policy_quiet_hours_behavior', $constraint$CHECK (quiet_hours_behavior IN ('DEFER','SUPPRESS','BYPASS'))$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'push_token', 'ck_push_token_provider', $constraint$CHECK (provider IN ('APNS','FCM'))$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'push_token', 'ck_push_token_status', $constraint$CHECK (status IN ('ACTIVE','INVALID'))$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification', 'ck_notification_channel', $constraint$CHECK (channel IN ('PUSH','EMAIL','IN_APP'))$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification', 'ck_notification_status', $constraint$CHECK (status IN ('PENDING','SENT','DELIVERED','FAILED','SUPPRESSED'))$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification_delivery_attempt', 'ck_notification_delivery_attempt_status', $constraint$CHECK (status IN ('STARTED','ACCEPTED','DELIVERED','FAILED','EXPIRED'))$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_intent', 'ck_nlp_intent_intent_type', $constraint$CHECK (intent_type IN ('WANT','OFFER'))$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_intent', 'ck_nlp_intent_status', $constraint$CHECK (status IN ('PROCESSING','MATCH_READY','FAILED','INACTIVE'))$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_embedding', 'ck_nlp_embedding_status', $constraint$CHECK (status IN ('ACTIVE','SUPERSEDED','FAILED'))$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_embedding', 'ck_nlp_embedding_dimensions', $constraint$CHECK (dimensions = 1536)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_model_version', 'ck_nlp_model_version_status', $constraint$CHECK (status IN ('CANDIDATE','ACTIVE','RETIRED','ROLLED_BACK'))$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_model_version', 'ck_nlp_model_version_dimensions', $constraint$CHECK (dimensions = 1536)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_processing_job', 'ck_nlp_processing_job_job_type', $constraint$CHECK (job_type IN ('EMBED','REEMBED'))$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_processing_job', 'ck_nlp_processing_job_status', $constraint$CHECK (status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','DEAD'))$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'match_request', 'ck_match_request_status', $constraint$CHECK (status IN ('PROCESSING','COMPLETED','FAILED'))$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_feedback', 'ck_nlp_feedback_label', $constraint$CHECK (label IN ('USEFUL','NOT_USEFUL','INAPPROPRIATE'))$constraint$);
SELECT ops.add_constraint_if_missing('core', 'member_profile', 'ck_member_profile_completeness', $constraint$CHECK (completeness_score BETWEEN 0 AND 100)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event', 'ck_event_date_range', $constraint$CHECK (ends_at > starts_at)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event_matching_policy', 'ck_event_matching_policy_thresholds', $constraint$CHECK ((match_threshold_override IS NULL OR match_threshold_override BETWEEN 0 AND 1) AND alert_confidence_threshold BETWEEN 0 AND 1)$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event_matching_policy', 'ck_event_matching_policy_limits', $constraint$CHECK (max_match_alerts_per_hour >= 0 AND max_match_alerts_per_event >= 0 AND minimum_alert_interval_minutes >= 0 AND (effective_to IS NULL OR effective_to > effective_from))$constraint$);
SELECT ops.add_constraint_if_missing('event', 'event_matching_policy', 'ck_event_matching_policy_proximity', $constraint$CHECK ((check_in_required IS FALSE OR registration_required IS TRUE) AND (proximity_mode <> 'COARSE_CELL' OR (live_mode_required IS TRUE AND max_presence_age_minutes IS NOT NULL AND max_presence_age_minutes > 0)))$constraint$);
SELECT ops.add_constraint_if_missing('social', 'connection_request', 'ck_connection_request_members', $constraint$CHECK (sender_member_id <> recipient_member_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'connection_request', 'ck_connection_request_expiry', $constraint$CHECK (expires_at > created_at)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'connection', 'ck_connection_canonical_pair', $constraint$CHECK (member_low_id < member_high_id)$constraint$);
SELECT ops.add_constraint_if_missing('social', 'member_block', 'ck_member_block_members', $constraint$CHECK (blocker_member_id <> blocked_member_id)$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification_policy', 'ck_notification_policy_limits', $constraint$CHECK (dedupe_window_seconds > 0 AND max_per_hour > 0 AND max_per_day > 0 AND max_attempts > 0 AND ttl_minutes > 0 AND (effective_to IS NULL OR effective_to > effective_from))$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification', 'ck_notification_confidence', $constraint$CHECK (source_confidence IS NULL OR source_confidence BETWEEN 0 AND 1)$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification', 'ck_notification_expiry', $constraint$CHECK (expires_at > created_at)$constraint$);
SELECT ops.add_constraint_if_missing('notification', 'notification_delivery_attempt', 'ck_notification_delivery_attempt_attempt', $constraint$CHECK (attempt_number > 0 AND (duration_ms IS NULL OR duration_ms >= 0))$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_ranking_config', 'ck_nlp_ranking_config_weights', $constraint$CHECK (semantic_weight BETWEEN 0 AND 1 AND category_weight BETWEEN 0 AND 1 AND industry_weight BETWEEN 0 AND 1 AND geography_weight BETWEEN 0 AND 1 AND freshness_weight BETWEEN 0 AND 1 AND event_weight BETWEEN 0 AND 1 AND threshold BETWEEN 0 AND 1)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'match_request', 'ck_match_request_limit', $constraint$CHECK (requested_limit BETWEEN 3 AND 7)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'nlp_match_result', 'ck_nlp_match_result_scores', $constraint$CHECK (semantic_score BETWEEN 0 AND 1 AND (reciprocal_score IS NULL OR reciprocal_score BETWEEN 0 AND 1) AND final_score BETWEEN 0 AND 1 AND rank > 0)$constraint$);
SELECT ops.add_constraint_if_missing('nlp', 'match_suppression', 'ck_match_suppression_target', $constraint$CHECK ((member_id IS NOT NULL OR intent_id IS NOT NULL OR context_id IS NOT NULL) AND (ends_at IS NULL OR ends_at > starts_at))$constraint$);
CREATE UNIQUE INDEX IF NOT EXISTS ux_community_name ON core.community (name);
CREATE UNIQUE INDEX IF NOT EXISTS ux_member_identity_provider_subject_hash ON iam.member_identity (provider, provider_subject_hash);
CREATE UNIQUE INDEX IF NOT EXISTS ux_member_identity_primary ON iam.member_identity (member_id) WHERE is_primary IS TRUE;
CREATE UNIQUE INDEX IF NOT EXISTS ux_role_name ON iam.role (name);
CREATE UNIQUE INDEX IF NOT EXISTS ux_organization_community_name ON core.organization (community_id, normalized_name);
CREATE UNIQUE INDEX IF NOT EXISTS ux_organization_member_active ON core.organization_member (organization_id, member_id) WHERE ended_on IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_member_sector_primary ON core.member_sector (member_id) WHERE is_primary IS TRUE;
CREATE UNIQUE INDEX IF NOT EXISTS ux_member_geography_primary ON core.member_geography (member_id) WHERE is_primary IS TRUE;
CREATE UNIQUE INDEX IF NOT EXISTS ux_consent_policy_purpose_version_locale ON consent.consent_policy (purpose_code, version, locale);
CREATE UNIQUE INDEX IF NOT EXISTS ux_event_matching_policy_version ON event.event_matching_policy (event_id, policy_version);
CREATE UNIQUE INDEX IF NOT EXISTS ux_event_matching_policy_active ON event.event_matching_policy (event_id) WHERE status = 'ACTIVE';
CREATE UNIQUE INDEX IF NOT EXISTS ux_event_registration_event_member ON event.event_registration (event_id, member_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_live_mode_session_active ON event.live_mode_session (event_id, member_id) WHERE status = 'ACTIVE';
CREATE UNIQUE INDEX IF NOT EXISTS ux_connection_request_open_pair ON social.connection_request (sender_member_id, recipient_member_id) WHERE status = 'PENDING';
CREATE UNIQUE INDEX IF NOT EXISTS ux_connection_pair ON social.connection (member_low_id, member_high_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_connection_accepted_request ON social.connection (accepted_request_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_member_block_active ON social.member_block (blocker_member_id, blocked_member_id) WHERE removed_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_conversation_connection ON chat.conversation (connection_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_message_conversation_message ON chat.message (conversation_id, message_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_policy_version ON notification.notification_policy (community_id, purpose_code, channel, policy_version) NULLS NOT DISTINCT;
CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_policy_active ON notification.notification_policy (community_id, purpose_code, channel) NULLS NOT DISTINCT WHERE status = 'ACTIVE';
CREATE UNIQUE INDEX IF NOT EXISTS ux_push_token_fingerprint ON notification.push_token (token_fingerprint);
CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_dedupe ON notification.notification (member_id, channel, dedupe_key, dedupe_bucket_start);
CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_attempt_number ON notification.notification_delivery_attempt (notification_id, attempt_number);
CREATE UNIQUE INDEX IF NOT EXISTS ux_nlp_embedding_hash_model ON nlp.nlp_embedding (intent_id, normalized_hash, model_version);
CREATE UNIQUE INDEX IF NOT EXISTS ux_nlp_model_version_active ON nlp.nlp_model_version (status) WHERE status = 'ACTIVE';
CREATE UNIQUE INDEX IF NOT EXISTS ux_nlp_ranking_config_active ON nlp.nlp_ranking_config (active_to) NULLS NOT DISTINCT WHERE active_to IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_nlp_processing_job_active ON nlp.nlp_processing_job (intent_id, job_type) WHERE status IN ('PENDING','RUNNING');
CREATE UNIQUE INDEX IF NOT EXISTS ux_nlp_match_result_request_candidate ON nlp.nlp_match_result (request_id, candidate_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_nlp_match_result_request_rank ON nlp.nlp_match_result (request_id, rank);
CREATE UNIQUE INDEX IF NOT EXISTS ux_nlp_feedback_original ON nlp.nlp_feedback (match_result_id, requester_id) WHERE supersedes_feedback_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_nlp_feedback_superseded ON nlp.nlp_feedback (supersedes_feedback_id) WHERE supersedes_feedback_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_evaluation_dataset_name_version ON nlp.evaluation_dataset (name, version);
CREATE INDEX IF NOT EXISTS ix_member_community_status ON iam.member (community_id, status);
CREATE INDEX IF NOT EXISTS ix_member_profile_discovery ON core.member_profile (profile_status, visibility, updated_at);
CREATE INDEX IF NOT EXISTS ix_event_community_status_start ON event.event (community_id, status, starts_at);
CREATE INDEX IF NOT EXISTS ix_event_presence_cell_expiry ON event.event_presence (coarse_cell, expires_at);
CREATE INDEX IF NOT EXISTS ix_connection_request_recipient_status_expiry ON social.connection_request (recipient_member_id, status, expires_at, created_at);
CREATE INDEX IF NOT EXISTS ix_message_conversation_sequence ON chat.message (conversation_id, server_sequence);
CREATE INDEX IF NOT EXISTS ix_notification_due ON notification.notification (status, scheduled_at, expires_at);
CREATE INDEX IF NOT EXISTS ix_notification_rate_limit ON notification.notification (member_id, notification_policy_id, created_at);
CREATE INDEX IF NOT EXISTS ix_notification_event_limit ON notification.notification (member_id, event_matching_policy_id, context_id, created_at);
CREATE INDEX IF NOT EXISTS ix_notification_attempt_retry ON notification.notification_delivery_attempt (status, next_attempt_at);
CREATE INDEX IF NOT EXISTS ix_nlp_intent_context_type_status_expiry ON nlp.nlp_intent (context_id, intent_type, status, expires_at);
CREATE INDEX IF NOT EXISTS ix_match_request_requester_created ON nlp.match_request (requester_id, created_at);
CREATE INDEX IF NOT EXISTS ix_nlp_match_result_candidate_created ON nlp.nlp_match_result (candidate_id, created_at);
CREATE INDEX IF NOT EXISTS ix_outbox_event_due ON ops.outbox_event (published_at, next_attempt_at);
CREATE INDEX IF NOT EXISTS ix_background_job_due ON ops.background_job (status, available_at);
CREATE INDEX IF NOT EXISTS ix_idempotency_record_expiry ON ops.idempotency_record (expires_at);
CREATE INDEX IF NOT EXISTS ix_product_event_name_occurred ON analytics.product_event (event_name, occurred_at);
CREATE INDEX IF NOT EXISTS ix_member_role_granted_by ON iam.member_role (granted_by);
CREATE INDEX IF NOT EXISTS ix_member_verification_evidence_file_asset_id ON core.member_verification (evidence_file_asset_id);
CREATE INDEX IF NOT EXISTS ix_member_verification_reviewed_by ON core.member_verification (reviewed_by);
CREATE INDEX IF NOT EXISTS ix_privacy_request_result_file_asset_id ON consent.privacy_request (result_file_asset_id);
CREATE INDEX IF NOT EXISTS ix_live_mode_session_consent_record_id ON event.live_mode_session (consent_record_id);
CREATE INDEX IF NOT EXISTS ix_connection_request_match_result_id ON social.connection_request (match_result_id);
CREATE INDEX IF NOT EXISTS ix_member_report_reporter_member_id ON social.member_report (reporter_member_id);
CREATE INDEX IF NOT EXISTS ix_conversation_participant_last_read_message_id ON chat.conversation_participant (last_read_message_id);
CREATE INDEX IF NOT EXISTS ix_notification_notification_policy_id ON notification.notification (notification_policy_id);
CREATE INDEX IF NOT EXISTS ix_notification_event_matching_policy_id ON notification.notification (event_matching_policy_id);
CREATE INDEX IF NOT EXISTS ix_notification_delivery_attempt_push_token_id ON notification.notification_delivery_attempt (push_token_id);
CREATE INDEX IF NOT EXISTS ix_nlp_embedding_model_version ON nlp.nlp_embedding (model_version);
CREATE INDEX IF NOT EXISTS ix_match_request_intent_id ON nlp.match_request (intent_id);
CREATE INDEX IF NOT EXISTS ix_match_request_model_version ON nlp.match_request (model_version);
CREATE INDEX IF NOT EXISTS ix_match_request_ranking_version ON nlp.match_request (ranking_version);
CREATE INDEX IF NOT EXISTS ix_nlp_match_result_requester_id ON nlp.nlp_match_result (requester_id);
CREATE INDEX IF NOT EXISTS ix_nlp_match_result_model_version ON nlp.nlp_match_result (model_version);
CREATE INDEX IF NOT EXISTS ix_nlp_match_result_ranking_version ON nlp.nlp_match_result (ranking_version);
CREATE INDEX IF NOT EXISTS ix_nlp_feedback_request_id ON nlp.nlp_feedback (request_id);
CREATE INDEX IF NOT EXISTS ix_nlp_feedback_requester_id ON nlp.nlp_feedback (requester_id);
CREATE INDEX IF NOT EXISTS ix_nlp_feedback_candidate_id ON nlp.nlp_feedback (candidate_id);
CREATE INDEX IF NOT EXISTS ix_match_suppression_created_by ON nlp.match_suppression (created_by);
CREATE INDEX IF NOT EXISTS ix_evaluation_dataset_approved_by ON nlp.evaluation_dataset (approved_by);
CREATE INDEX IF NOT EXISTS ix_evaluation_run_ranking_version ON nlp.evaluation_run (ranking_version);
CREATE INDEX IF NOT EXISTS ix_moderation_case_assigned_to ON moderation.moderation_case (assigned_to);
CREATE INDEX IF NOT EXISTS ix_content_rule_created_by ON moderation.content_rule (created_by);
-- v2.3 cross-domain foreign keys.
SELECT ops.add_constraint_if_missing('iam', 'role_permission', 'fk_role_permission_role_code', $constraint$FOREIGN KEY (role_code) REFERENCES iam.role (role_code)$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'role_permission', 'fk_role_permission_permission_code', $constraint$FOREIGN KEY (permission_code) REFERENCES iam.permission (permission_code)$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'role_permission', 'fk_role_permission_granted_by', $constraint$FOREIGN KEY (granted_by) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'auth_session', 'fk_auth_session_member_id', $constraint$FOREIGN KEY (member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'auth_session', 'fk_auth_session_device_id', $constraint$FOREIGN KEY (device_id) REFERENCES iam.member_device (device_id)$constraint$);
SELECT ops.add_constraint_if_missing('consent', 'privacy_request_task', 'fk_privacy_request_task_privacy_request_id', $constraint$FOREIGN KEY (privacy_request_id) REFERENCES consent.privacy_request (privacy_request_id)$constraint$);
SELECT ops.add_constraint_if_missing('storage', 'file_asset', 'fk_file_asset_community_id', $constraint$FOREIGN KEY (community_id) REFERENCES core.community (community_id)$constraint$);
SELECT ops.add_constraint_if_missing('storage', 'file_asset', 'fk_file_asset_owner_member_id', $constraint$FOREIGN KEY (owner_member_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('storage', 'file_asset_link', 'fk_file_asset_link_file_asset_id', $constraint$FOREIGN KEY (file_asset_id) REFERENCES storage.file_asset (file_asset_id)$constraint$);
SELECT ops.add_constraint_if_missing('storage', 'file_asset_link', 'fk_file_asset_link_linked_by', $constraint$FOREIGN KEY (linked_by) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('ops', 'sync_change', 'fk_sync_change_community_id', $constraint$FOREIGN KEY (community_id) REFERENCES core.community (community_id)$constraint$);
SELECT ops.add_constraint_if_missing('ops', 'sync_change', 'fk_sync_change_member_scope_id', $constraint$FOREIGN KEY (member_scope_id) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('ops', 'retention_policy', 'fk_retention_policy_approved_by', $constraint$FOREIGN KEY (approved_by) REFERENCES iam.member (member_id)$constraint$);
SELECT ops.add_constraint_if_missing('ops', 'retention_execution', 'fk_retention_execution_retention_policy_id', $constraint$FOREIGN KEY (retention_policy_id) REFERENCES ops.retention_policy (retention_policy_id)$constraint$);
-- v2.3 state, lifecycle and bounded-value constraints.
SELECT ops.add_constraint_if_missing('iam', 'permission', 'ck_permission_action', $constraint$CHECK (action IN ('READ','CREATE','UPDATE','DELETE','APPROVE','EXPORT','CONFIGURE'))$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'permission', 'ck_permission_status', $constraint$CHECK (status IN ('ACTIVE','RETIRED'))$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'role_permission', 'ck_role_permission_dates', $constraint$CHECK (revoked_at IS NULL OR revoked_at >= granted_at)$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'auth_session', 'ck_auth_session_auth_strength', $constraint$CHECK (auth_strength IN ('STANDARD','MFA','STEP_UP'))$constraint$);
SELECT ops.add_constraint_if_missing('iam', 'auth_session', 'ck_auth_session_dates', $constraint$CHECK (expires_at > issued_at AND last_seen_at >= issued_at AND (revoked_at IS NULL OR revoked_at >= issued_at))$constraint$);
SELECT ops.add_constraint_if_missing('consent', 'privacy_request_task', 'ck_privacy_request_task_domain', $constraint$CHECK (domain_code IN ('IAM','PROFILE','EVENT','SOCIAL','CHAT','STORAGE','NLP','ANALYTICS','AUDIT'))$constraint$);
SELECT ops.add_constraint_if_missing('consent', 'privacy_request_task', 'ck_privacy_request_task_action', $constraint$CHECK (action_type IN ('EXPORT','CORRECT','ANONYMIZE','DELETE','RETAIN_EXCEPTION'))$constraint$);
SELECT ops.add_constraint_if_missing('consent', 'privacy_request_task', 'ck_privacy_request_task_state', $constraint$CHECK (status IN ('PENDING','RUNNING','COMPLETED','FAILED','EXEMPTED') AND attempt_count >= 0 AND (status NOT IN ('COMPLETED','EXEMPTED') OR (completed_at IS NOT NULL AND evidence_code IS NOT NULL)))$constraint$);
SELECT ops.add_constraint_if_missing('storage', 'file_asset', 'ck_file_asset_purpose', $constraint$CHECK (purpose_code IN ('CHAT_FILE','VERIFICATION_EVIDENCE','PRIVACY_EXPORT','EVALUATION_REPORT'))$constraint$);
SELECT ops.add_constraint_if_missing('storage', 'file_asset', 'ck_file_asset_classification', $constraint$CHECK (classification IN ('INTERNAL','CONFIDENTIAL','RESTRICTED','HIGHLY_RESTRICTED'))$constraint$);
SELECT ops.add_constraint_if_missing('storage', 'file_asset', 'ck_file_asset_lifecycle', $constraint$CHECK (size_bytes >= 0 AND scan_status IN ('PENDING','CLEAN','REJECTED','ERROR') AND lifecycle_status IN ('UPLOADING','AVAILABLE','QUARANTINED','DELETED','EXPIRED') AND (lifecycle_status <> 'AVAILABLE' OR scan_status = 'CLEAN') AND (lifecycle_status NOT IN ('DELETED','EXPIRED') OR deleted_at IS NOT NULL))$constraint$);
SELECT ops.add_constraint_if_missing('storage', 'file_asset_link', 'ck_file_asset_link_values', $constraint$CHECK (resource_type IN ('MESSAGE','MEMBER_VERIFICATION','PRIVACY_REQUEST','EVALUATION_RUN') AND relationship_type IN ('PRIMARY','EVIDENCE','RESULT','REPORT'))$constraint$);
SELECT ops.add_constraint_if_missing('ops', 'sync_change', 'ck_sync_change_values', $constraint$CHECK (change_type IN ('UPSERT','DELETE') AND resource_type IN ('PROFILE','MATCH','REQUEST','CONVERSATION','MESSAGE','NOTIFICATION') AND expires_at > occurred_at)$constraint$);
SELECT ops.add_constraint_if_missing('ops', 'idempotency_record', 'ck_idempotency_record_completion', $constraint$CHECK (expires_at > created_at AND (status_code IS NULL OR status_code BETWEEN 100 AND 599) AND ((status_code IS NULL) = (response_ref IS NULL)))$constraint$);
SELECT ops.add_constraint_if_missing('ops', 'retention_policy', 'ck_retention_policy_values', $constraint$CHECK (policy_version > 0 AND retention_days >= 0 AND status IN ('DRAFT','ACTIVE','RETIRED') AND disposition_action IN ('DELETE','ANONYMIZE','ARCHIVE') AND (effective_to IS NULL OR effective_to > effective_from))$constraint$);
SELECT ops.add_constraint_if_missing('ops', 'retention_execution', 'ck_retention_execution_values', $constraint$CHECK (scope_end > scope_start AND status IN ('RUNNING','SUCCEEDED','PARTIAL','FAILED') AND examined_count >= 0 AND disposed_count >= 0 AND skipped_hold_count >= 0 AND disposed_count + skipped_hold_count <= examined_count AND (status = 'RUNNING' OR completed_at IS NOT NULL))$constraint$);
-- v2.3 lookup, uniqueness and worker access paths.
CREATE UNIQUE INDEX IF NOT EXISTS ux_permission_resource_action ON iam.permission (resource_type, action);
CREATE INDEX IF NOT EXISTS ix_permission_status ON iam.permission (status);
CREATE INDEX IF NOT EXISTS ix_role_permission_permission_revoked ON iam.role_permission (permission_code, revoked_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_auth_session_provider_session_hash ON iam.auth_session (provider_session_hash) WHERE provider_session_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_auth_session_member_active ON iam.auth_session (member_id, revoked_at, expires_at);
CREATE INDEX IF NOT EXISTS ix_auth_session_device_revoked ON iam.auth_session (device_id, revoked_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_privacy_request_task_domain_action ON consent.privacy_request_task (privacy_request_id, domain_code, action_type);
CREATE INDEX IF NOT EXISTS ix_privacy_request_task_due_work ON consent.privacy_request_task (status, updated_at);
-- Long blob paths can exceed PostgreSQL B-tree entry limits; the hash is unique and full paths are collision-checked by the service.
CREATE UNIQUE INDEX IF NOT EXISTS ux_file_asset_blob_path_hash ON storage.file_asset (blob_path_hash);
CREATE INDEX IF NOT EXISTS ix_file_asset_owner_created ON storage.file_asset (owner_member_id, created_at);
CREATE INDEX IF NOT EXISTS ix_file_asset_lifecycle_expiry ON storage.file_asset (purpose_code, lifecycle_status, expires_at);
CREATE INDEX IF NOT EXISTS ix_file_asset_scan_queue ON storage.file_asset (scan_status, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_file_asset_link_resource ON storage.file_asset_link (file_asset_id, resource_type, resource_id, relationship_type);
CREATE INDEX IF NOT EXISTS ix_file_asset_link_resource ON storage.file_asset_link (resource_type, resource_id, removed_at);
CREATE INDEX IF NOT EXISTS ix_sync_change_community_cursor ON ops.sync_change (community_id, sync_sequence);
CREATE INDEX IF NOT EXISTS ix_sync_change_member_cursor ON ops.sync_change (member_scope_id, sync_sequence);
CREATE INDEX IF NOT EXISTS ix_sync_change_expiry ON ops.sync_change (expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_retention_policy_version ON ops.retention_policy (resource_type, policy_version);
CREATE UNIQUE INDEX IF NOT EXISTS ux_retention_policy_active ON ops.retention_policy (resource_type) WHERE status = 'ACTIVE';
CREATE INDEX IF NOT EXISTS ix_retention_policy_status_effective ON ops.retention_policy (status, effective_from);
CREATE INDEX IF NOT EXISTS ix_retention_execution_policy_started ON ops.retention_execution (retention_policy_id, started_at DESC);
CREATE INDEX IF NOT EXISTS ix_retention_execution_status_started ON ops.retention_execution (status, started_at);
-- Documented v2.3 access paths not already covered by a matching key.
CREATE INDEX IF NOT EXISTS ix_community_status ON core.community (status);
CREATE INDEX IF NOT EXISTS ix_organization_website_domain ON core.organization (website_domain);
CREATE UNIQUE INDEX IF NOT EXISTS uq_organization_member_organization_id_member_id_started_on ON core.organization_member (organization_id, member_id, started_on);
CREATE INDEX IF NOT EXISTS ix_organization_member_member_id_is_primary ON core.organization_member (member_id, is_primary);
CREATE INDEX IF NOT EXISTS ix_member_profile_updated_at ON core.member_profile (updated_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sector_name ON core.sector (name);
CREATE INDEX IF NOT EXISTS ix_sector_parent_sector_code_status ON core.sector (parent_sector_code, status);
CREATE INDEX IF NOT EXISTS ix_member_sector_sector_code_member_id ON core.member_sector (sector_code, member_id);
CREATE INDEX IF NOT EXISTS ix_member_geography_member_id_is_primary ON core.member_geography (member_id, is_primary);
CREATE INDEX IF NOT EXISTS ix_member_geography_country_code_region_city ON core.member_geography (country_code, region, city);
CREATE INDEX IF NOT EXISTS ix_profile_field_visibility_audience ON core.profile_field_visibility (audience);
CREATE INDEX IF NOT EXISTS ix_member_verification_member_id_status ON core.member_verification (member_id, status);
CREATE INDEX IF NOT EXISTS ix_member_verification_status_created_at ON core.member_verification (status, created_at);
CREATE INDEX IF NOT EXISTS ix_member_status_updated_at ON iam.member (status, updated_at);
CREATE INDEX IF NOT EXISTS ix_member_identity_member_id_is_primary ON iam.member_identity (member_id, is_primary);
CREATE INDEX IF NOT EXISTS ix_member_identity_member_id_status ON iam.member_identity (member_id, status);
CREATE INDEX IF NOT EXISTS ix_role_status ON iam.role (status);
CREATE INDEX IF NOT EXISTS ix_member_role_role_code_expires_at ON iam.member_role (role_code, expires_at);
CREATE INDEX IF NOT EXISTS ix_member_device_member_id_status ON iam.member_device (member_id, status);
CREATE INDEX IF NOT EXISTS ix_member_device_last_seen_at ON iam.member_device (last_seen_at);
CREATE INDEX IF NOT EXISTS ix_consent_policy_purpose_code_effective_from ON consent.consent_policy (purpose_code, effective_from);
CREATE INDEX IF NOT EXISTS ix_member_consent_member_id_policy_id_captured_at ON consent.member_consent (member_id, policy_id, captured_at);
CREATE INDEX IF NOT EXISTS ix_member_consent_policy_id_decision ON consent.member_consent (policy_id, decision);
CREATE INDEX IF NOT EXISTS ix_privacy_request_status_due_at ON consent.privacy_request (status, due_at);
CREATE INDEX IF NOT EXISTS ix_privacy_request_member_id_created_at ON consent.privacy_request (member_id, created_at);
CREATE INDEX IF NOT EXISTS ix_venue_country_code_region_city ON event.venue (country_code, region, city);
CREATE INDEX IF NOT EXISTS ix_venue_status_country_code_region_city ON event.venue (status, country_code, region, city);
CREATE INDEX IF NOT EXISTS ix_event_venue_id_starts_at ON event.event (venue_id, starts_at);
CREATE INDEX IF NOT EXISTS ix_event_matching_policy_status_effective_from_effective_to ON event.event_matching_policy (status, effective_from, effective_to);
CREATE INDEX IF NOT EXISTS ix_event_registration_member_id_status ON event.event_registration (member_id, status);
CREATE INDEX IF NOT EXISTS ix_event_registration_event_id_status ON event.event_registration (event_id, status);
CREATE INDEX IF NOT EXISTS ix_live_mode_session_event_id_status_active_until ON event.live_mode_session (event_id, status, active_until);
CREATE INDEX IF NOT EXISTS ix_live_mode_session_member_id_status ON event.live_mode_session (member_id, status);
CREATE INDEX IF NOT EXISTS ix_event_presence_live_session_id_observed_at ON event.event_presence (live_session_id, observed_at);
CREATE INDEX IF NOT EXISTS ix_connection_request_sender_member_id_status ON social.connection_request (sender_member_id, status);
CREATE INDEX IF NOT EXISTS ix_connection_member_low_id_status ON social.connection (member_low_id, status);
CREATE INDEX IF NOT EXISTS ix_connection_member_high_id_status ON social.connection (member_high_id, status);
CREATE INDEX IF NOT EXISTS ix_member_block_blocked_member_id_removed_at ON social.member_block (blocked_member_id, removed_at);
CREATE INDEX IF NOT EXISTS ix_member_report_status_created_at ON social.member_report (status, created_at);
CREATE INDEX IF NOT EXISTS ix_member_report_reported_member_id_created_at ON social.member_report (reported_member_id, created_at);
CREATE INDEX IF NOT EXISTS ix_conversation_status_last_message_at ON chat.conversation (status, last_message_at);
CREATE INDEX IF NOT EXISTS ix_conversation_participant_member_id_left_at ON chat.conversation_participant (member_id, left_at);
CREATE INDEX IF NOT EXISTS ix_message_sender_member_id_created_at ON chat.message (sender_member_id, created_at);
CREATE INDEX IF NOT EXISTS ix_message_receipt_member_id_read_at ON chat.message_receipt (member_id, read_at);
CREATE INDEX IF NOT EXISTS ix_notification_policy_status_effective_from_effective_to ON notification.notification_policy (status, effective_from, effective_to);
CREATE INDEX IF NOT EXISTS ix_push_token_device_id_status ON notification.push_token (device_id, status);
CREATE INDEX IF NOT EXISTS ix_notification_member_id_created_at ON notification.notification (member_id, created_at);
CREATE INDEX IF NOT EXISTS ix_notification_delivery_attempt_provider_provider_message_id ON notification.notification_delivery_attempt (provider, provider_message_id);
CREATE INDEX IF NOT EXISTS ix_nlp_intent_member_id_status ON nlp.nlp_intent (member_id, status);
CREATE INDEX IF NOT EXISTS ix_nlp_intent_normalized_hash ON nlp.nlp_intent (normalized_hash);
CREATE INDEX IF NOT EXISTS ix_nlp_model_version_status_created_at ON nlp.nlp_model_version (status, created_at);
CREATE INDEX IF NOT EXISTS ix_nlp_ranking_config_active_from_active_to ON nlp.nlp_ranking_config (active_from, active_to);
CREATE INDEX IF NOT EXISTS ix_nlp_processing_job_status_available_at ON nlp.nlp_processing_job (status, available_at);
CREATE INDEX IF NOT EXISTS ix_match_request_status_created_at ON nlp.match_request (status, created_at);
CREATE INDEX IF NOT EXISTS ix_match_request_request_hash ON nlp.match_request (request_hash);
CREATE INDEX IF NOT EXISTS ix_nlp_feedback_label_created_at ON nlp.nlp_feedback (label, created_at);
CREATE INDEX IF NOT EXISTS ix_match_suppression_member_id_context_id_ends_at ON nlp.match_suppression (member_id, context_id, ends_at);
CREATE INDEX IF NOT EXISTS ix_match_suppression_intent_id_ends_at ON nlp.match_suppression (intent_id, ends_at);
CREATE INDEX IF NOT EXISTS ix_evaluation_dataset_status_created_at ON nlp.evaluation_dataset (status, created_at);
CREATE INDEX IF NOT EXISTS ix_evaluation_pair_dataset_id_split ON nlp.evaluation_pair (dataset_id, split);
CREATE INDEX IF NOT EXISTS ix_evaluation_pair_gold_label ON nlp.evaluation_pair (gold_label);
CREATE INDEX IF NOT EXISTS ix_evaluation_run_dataset_id_started_at ON nlp.evaluation_run (dataset_id, started_at);
CREATE INDEX IF NOT EXISTS ix_evaluation_run_model_version_ranking_version ON nlp.evaluation_run (model_version, ranking_version);
CREATE INDEX IF NOT EXISTS ix_moderation_case_status_priority_created_at ON moderation.moderation_case (status, priority, created_at);
CREATE INDEX IF NOT EXISTS ix_moderation_case_subject_member_id_created_at ON moderation.moderation_case (subject_member_id, created_at);
CREATE INDEX IF NOT EXISTS ix_moderation_action_moderation_case_id_created_at ON moderation.moderation_action (moderation_case_id, created_at);
CREATE INDEX IF NOT EXISTS ix_moderation_action_actor_member_id_created_at ON moderation.moderation_action (actor_member_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_content_rule_rule_type_version ON moderation.content_rule (rule_type, version);
CREATE INDEX IF NOT EXISTS ix_content_rule_rule_type_status ON moderation.content_rule (rule_type, status);
CREATE INDEX IF NOT EXISTS ix_content_scan_resource_type_resource_id_scanned_at ON moderation.content_scan (resource_type, resource_id, scanned_at);
CREATE INDEX IF NOT EXISTS ix_content_scan_result_scanned_at ON moderation.content_scan (result, scanned_at);
CREATE INDEX IF NOT EXISTS ix_outbox_event_aggregate_type_aggregate_id_occurred_at ON ops.outbox_event (aggregate_type, aggregate_id, occurred_at);
CREATE INDEX IF NOT EXISTS ix_background_job_resource_type_resource_id ON ops.background_job (resource_type, resource_id);
CREATE INDEX IF NOT EXISTS ix_audit_event_resource_type_resource_id_occurred_at ON ops.audit_event (resource_type, resource_id, occurred_at);
CREATE INDEX IF NOT EXISTS ix_audit_event_actor_id_occurred_at ON ops.audit_event (actor_id, occurred_at);
CREATE INDEX IF NOT EXISTS ix_audit_event_correlation_id ON ops.audit_event (correlation_id);
CREATE INDEX IF NOT EXISTS ix_product_event_community_id_occurred_at ON analytics.product_event (community_id, occurred_at);

DROP FUNCTION ops.add_constraint_if_missing(name, name, name, text);
